"""The committed pane fixture is what the backend produces (feature 009 T023).

`extractor/SwReview.AddIn.Tests/Fixtures/review-big-assembly.json` is the one file the Review
tab's acceptance tests load, so it must be exactly `review_snapshot` of the big-assembly replay
fixture plus the labels - regenerated by a command, never edited by hand (research R2.24). The
repository is public, so it is checked the way the replay fixtures are: every path sits under
the fictional root here, and `test_replay_fixture_hygiene.py` runs its string checks - drive
paths, email, URL and copyright, the recorded design ids, the forbidden words and the owner's
denylist - over this file as well as over the replay fixtures.
"""

from __future__ import annotations

import json
from types import ModuleType
from typing import Any

import pytest

from swreview.ir.loader import load_package
from swreview.report.names import component_names
from swreview.report.session import load_session
from swreview.report.summary import load_words
from swreview.report.titles import TITLE_LENGTH, display_title
from tests.support.mechanical import load_generator
from tests.support.scramble import FICTIONAL_ROOT
from tests.unit.test_replay_fixture_hygiene import PANE_GENERATOR as GENERATOR
from tests.unit.test_review_summary import BIG_ASSEMBLY


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    return load_generator(GENERATOR)


@pytest.fixture(scope="module")
def committed(generator: ModuleType) -> str:
    target = generator.TARGET
    assert target.is_file(), f"{target} is missing; run `{generator.WRITE_COMMAND}` from reviewer/"
    # Text mode: the checkout's line endings are the platform's, the generator's too.
    return target.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def fixture(committed: str) -> dict[str, Any]:
    return json.loads(committed)


def test_the_committed_fixture_is_a_fresh_generation(generator: ModuleType, committed: str) -> None:
    fresh = generator.render(generator.pane_fixture())

    assert committed == fresh, (
        f"{generator.TARGET.name} differs from a fresh generation; run "
        f"`{generator.WRITE_COMMAND}` from reviewer/ and commit the result"
    )


def test_it_is_the_snapshot_plus_the_labels(fixture: dict[str, Any]) -> None:
    assert set(fixture) == {
        "run_id",
        "read_only",
        "read_only_reason",
        "chat_state",
        "last_seq",
        "document",
        "findings",
        "evidence_requests",
        "coverage",
        "ranking",
        "not_examined",
        "labels",
    }
    assert fixture["labels"] == load_words().labels.model_dump(mode="json")
    assert (fixture["read_only"], fixture["chat_state"]) == (False, "ended")
    assert fixture["ranking"]["summary"]["headline"] == "99 findings in 18 issues"


def test_its_titles_are_the_ones_a_person_reads(
    generator: ModuleType, fixture: dict[str, Any]
) -> None:
    """Decision 2A (research R2.28): the page prints `title` verbatim, so the fixture carries the
    display titles - whole and named - on its findings and its unfolded ranking rows, of the
    titles this build records (the generator's `with_current_titles`)."""
    session = generator.with_current_titles(load_session(BIG_ASSEMBLY / "session.json"))
    names = component_names(load_package(BIG_ASSEMBLY).package)
    shown = {finding.id: display_title(finding, names) for finding in session.findings}
    rows = [row for row in fixture["ranking"]["rows"] if "family" not in row]

    assert [finding["title"] for finding in fixture["findings"]] == list(shown.values())
    assert [row["title"] for row in rows] == [shown[row["finding_id"]] for row in rows]
    assert [title for title in shown.values() if "…" in title] == []
    assert max(len(title) for title in shown.values()) > TITLE_LENGTH


def test_the_document_path_sits_under_the_fictional_root(fixture: dict[str, Any]) -> None:
    """Every other drive path in the file is `test_replay_fixture_hygiene.py`'s to refuse."""
    assert fixture["document"]["path"].startswith(FICTIONAL_ROOT)
