using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using SwReview.Extractor.Guard;
using SwReview.Extractor.Sw;
using Xunit;

namespace SwReview.Extractor.Tests;

/// <summary>
/// Decision 21A (feature 004, 2026-09-25, the owner), T165. <see cref="ReadOnlyGuard"/> refused
/// feature creation only through three prefixes, so <c>FeatureFillet3</c>, <c>FeatureRevolve2</c>,
/// <c>InsertMirrorFeature2</c>, <c>InsertPart3</c>, <c>MirrorPart2</c>, the sheet-metal and pattern
/// creators and the like passed a read-only gate as bare names.
///
/// <b>The "Decision 21A" tables of <c>004-resilient-remodeler/contracts/guard-allowlist.md</c> are the
/// membership, and this class reads them</b>, as <see cref="DrawingFamilyDenylistTests"/> reads feature
/// 011's. They are generated by <c>extractor/tools/list-creation-members.ps1</c> from the interop and
/// never typed; <see cref="CreationFamilyCompletenessTests"/> reflects the same interop at test time to
/// prove them complete. Only <see cref="RemodelProbeGuard"/> exempts any member, for the throwaway part
/// it builds (<see cref="ThrowawayPartExemptionTests"/>).
/// </summary>
public class CreationFamilyDenylistTests
{
    internal const string AllowlistFileName = "guard-allowlist.md";

    internal const string Document = "specs/004-resilient-remodeler/contracts/guard-allowlist.md (decision 21A)";

    /// <summary>The header of the generated table of creation-grammar matches.</summary>
    internal const string TableHeader = "| Members refused (decision 21A) | Interface; already denied |";

    /// <summary>The header of the generated table of named creators the grammar does not reach.</summary>
    internal const string NamedHeader = "| Named creators refused (decision 21A) | Interface; what it builds |";

    /// <summary>The header of the generated table of grammar matches left allowed.</summary>
    internal const string ExclusionHeader = "| Not denied (decision 21A) | Why |";

    /// <summary>
    /// The reads the grammar reaches, left allowed by rule 3 of the contract. Written here a second
    /// time, beside the generator's copy, on purpose: this is the check of the generated "Not denied"
    /// table, in both directions.
    /// </summary>
    internal static readonly string[] ReadsTheGrammarReaches =
    {
        "FeatureById", "IFeatureById",
        "FeatureByName", "IFeatureByName",
        "FeatureByPositionReverse", "IFeatureByPositionReverse",
        "FeatureFolderLocation",
        "CreateMassProperty", "CreateMassProperty2",
        "CreateMeasure",
    };

    /// <summary>The grammar table, parsed: one row per interface.</summary>
    public static readonly IReadOnlyList<(string Family, string[] Members)> Table = DenylistTable.Parse(
        AllowlistFileName, Document, TableHeader, minimumRows: 4);

    /// <summary>The named-creator table, parsed: one row per interface and what it builds.</summary>
    public static readonly IReadOnlyList<(string Family, string[] Members)> Named = DenylistTable.Parse(
        AllowlistFileName, Document + " named creators", NamedHeader, minimumRows: 5);

    /// <summary>The names the grammar matched and the section leaves allowed.</summary>
    public static readonly IReadOnlyList<(string Family, string[] Members)> Exclusions = DenylistTable.Parse(
        AllowlistFileName, Document + " exclusions", ExclusionHeader, minimumRows: 5);

    /// <summary>Every (interface, member) pair the two denial tables name.</summary>
    internal static IEnumerable<(string Interface, string Member)> Rows() =>
        Table.Concat(Named).SelectMany(row => row.Members.Select(
            member => (DrawingFamilyDenylistTests.InterfaceOf(row), member)));

    /// <summary>The distinct bare names the two tables deny: the expected set, derived.</summary>
    public static IReadOnlyCollection<string> ExpectedMembers =>
        new HashSet<string>(Rows().Select(row => row.Member), StringComparer.OrdinalIgnoreCase);

    /// <summary>The distinct bare names the exclusion table leaves allowed.</summary>
    public static IReadOnlyCollection<string> ExcludedMembers =>
        new HashSet<string>(Exclusions.SelectMany(row => row.Members), StringComparer.OrdinalIgnoreCase);

    public static IEnumerable<object[]> EveryMember() =>
        ExpectedMembers.OrderBy(member => member, StringComparer.Ordinal)
            .Select(member => new object[] { member });

    public static IEnumerable<object[]> EveryQualifiedMember() =>
        Rows().Select(row => row.Interface + "." + row.Member)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(key => key, StringComparer.Ordinal)
            .Select(key => new object[] { key });

    public static IEnumerable<object[]> EveryExcludedMember() =>
        ExcludedMembers.OrderBy(member => member, StringComparer.Ordinal)
            .Select(member => new object[] { member });

    [Theory]
    [MemberData(nameof(EveryMember))]
    public void EveryMemberOfTheTablesIsRefused(string member)
    {
        MutatingCallError error = Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member));
        Assert.Equal(member, error.MemberName);
        Assert.Throws<MutatingCallError>(() => ReadOnlyCallGuard.Instance.Assert(member));
    }

    [Theory]
    [MemberData(nameof(EveryMember))]
    public void EveryMemberOfTheTablesIsRefusedWhateverItsCase(string member)
    {
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member.ToUpperInvariant()));
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member.ToLowerInvariant()));
    }

    /// <summary>
    /// Every spelling a call site could use, on every gate the product builds: interface-qualified,
    /// no gate passes one - not even <see cref="RemodelProbeGuard"/>, whose exemption is the bare
    /// names its host gates, and not <see cref="RemodelGuard"/> or <see cref="DrawingOpenGuard"/>,
    /// whose allowlists name none of them.
    /// </summary>
    [Theory]
    [MemberData(nameof(EveryQualifiedMember))]
    public void EveryMemberOfTheTablesIsRefusedQualifiedWithItsInterfaceByEveryGate(string key)
    {
        MutatingCallError error = Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(key));
        Assert.Equal(key, error.MemberName);

        foreach (ICallGuard gate in GuardAnswers.EveryGateTheProductBuilds())
        {
            Assert.Throws<MutatingCallError>(() => gate.Assert(key));
        }
    }

    /// <summary>
    /// Bare, every gate but <see cref="RemodelProbeGuard"/> refuses every member, and that one refuses
    /// every member but the throwaway part's own creation calls.
    /// </summary>
    [Theory]
    [MemberData(nameof(EveryMember))]
    public void EveryMemberOfTheTablesIsRefusedBareByEveryGateButTheProbesOwnExemptions(string member)
    {
        foreach (ICallGuard gate in GuardAnswers.EveryGateTheProductBuilds())
        {
            bool exempted = gate is RemodelProbeGuard
                && RemodelProbeGuard.ThrowawayPartCreationMembers.Contains(member, StringComparer.OrdinalIgnoreCase);
            if (exempted)
            {
                gate.Assert(member);
            }
            else
            {
                Assert.Throws<MutatingCallError>(() => gate.Assert(member));
            }
        }
    }

    /// <summary>
    /// The tables list only what is new; what an earlier table or a denied prefix refuses sits in the
    /// "already denied" column, so no denial is counted twice.
    /// </summary>
    [Fact]
    public void TheTablesAddNothingAnEarlierTableOrPrefixAlreadyDenied()
    {
        foreach (IReadOnlyCollection<string> earlier in new[]
                 {
                     StandardsDenylistTests.ExpectedMembers,
                     MechanicalChecksDenylistTests.ExpectedMembers,
                     DrawingFamilyDenylistTests.ExpectedMembers,
                     ImportRepairDenylistTests.ExpectedMembers,
                 })
        {
            Assert.Empty(ExpectedMembers.Intersect(earlier, StringComparer.OrdinalIgnoreCase));
        }

        Assert.DoesNotContain(
            ExpectedMembers,
            member => ReadOnlyGuard.DeniedPrefixes.Any(
                prefix => member.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)));
    }

    /// <summary>A named creator is one the grammar does not reach, so the two tables never overlap.</summary>
    [Fact]
    public void TheGrammarTableAndTheNamedTableShareNoMember()
    {
        var grammar = new HashSet<string>(Table.SelectMany(row => row.Members), StringComparer.OrdinalIgnoreCase);

        Assert.DoesNotContain(Named.SelectMany(row => row.Members), grammar.Contains);
    }

    /// <summary>
    /// Feature 004's allowlist is asserted against the read-only denied surface; a denial that shared a
    /// stage-1 key's bare name would change the keys that override a denial, and one of
    /// <see cref="RemodelGuard.ExcludedMembers"/> would make that list redundant.
    /// </summary>
    [Fact]
    public void NoMemberOfTheTablesIsAStage1KeyOrARemodelExclusion()
    {
        var bareKeys = new HashSet<string>(
            RemodelGuard.AllowedKeys.Select(CallKey.BareName), StringComparer.OrdinalIgnoreCase);

        Assert.DoesNotContain(ExpectedMembers, bareKeys.Contains);
        Assert.Empty(ExpectedMembers.Intersect(RemodelGuard.ExcludedMembers, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>A name the section leaves allowed is really allowed, and is not also on a table.</summary>
    [Theory]
    [MemberData(nameof(EveryExcludedMember))]
    public void EveryExcludedNameStaysAllowed(string member)
    {
        ReadOnlyGuard.Assert(member);
        ReadOnlyCallGuard.Instance.Assert(member);
        Assert.DoesNotContain(member, ExpectedMembers, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Every exclusion has one of rule 3's reasons - the bare name of a stage-1 allowlist key, a member
    /// <see cref="RemodelGuard"/> refuses itself, or one of the reads the grammar reaches - and every one
    /// of those reads is on the table, so the generator cannot drop one silently.
    /// </summary>
    [Fact]
    public void EveryExclusionHasOneOfTheContractsReasonsAndEveryReadIsExcluded()
    {
        var bareKeys = new HashSet<string>(
            RemodelGuard.AllowedKeys.Select(CallKey.BareName), StringComparer.OrdinalIgnoreCase);
        var reads = new HashSet<string>(ReadsTheGrammarReaches, StringComparer.OrdinalIgnoreCase);

        foreach (string member in ExcludedMembers)
        {
            Assert.True(
                bareKeys.Contains(member)
                    || RemodelGuard.ExcludedMembers.Contains(member, StringComparer.OrdinalIgnoreCase)
                    || reads.Contains(member),
                $"{member} is excluded from the decision 21A denials without a reason rule 3 gives.");
        }

        Assert.Empty(reads.Except(ExcludedMembers, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>
    /// The families the decision names are closed, whichever rule refuses each: decision 21A's tables
    /// for most, a denied prefix for the members the throwaway part already needed an exemption for.
    /// </summary>
    [Theory]
    [InlineData("FeatureFillet3")]
    [InlineData("FeatureFillet5")]
    [InlineData("FeatureRevolve2")]
    [InlineData("FeatureRevolveCut2")]
    [InlineData("InsertMirrorFeature2")]
    [InlineData("InsertPart3")]
    [InlineData("MirrorPart2")]
    [InlineData("MirrorFeature")]
    [InlineData("FeatureExtrusion3")]
    [InlineData("FeatureCut4")]
    [InlineData("InsertFeatureChamfer")]
    [InlineData("InsertFeatureShell")]
    [InlineData("InsertSheetMetalBaseFlange2")]
    [InlineData("InsertSheetMetalEdgeFlange2")]
    [InlineData("InsertConvertToSheetMetal2")]
    [InlineData("FeatureLinearPattern5")]
    [InlineData("FeatureCircularPattern5")]
    [InlineData("FeatureSketchDrivenPattern")]
    [InlineData("FeatureChainPattern")]
    [InlineData("InsertTableDrivenPattern2")]
    [InlineData("CreateFeatureFromBody3")]
    [InlineData("CreateFeature")]
    [InlineData("InsertRefPlane")]
    [InlineData("InsertSketch")]
    [InlineData("HoleWizard5")]
    [InlineData("SimpleHole2")]
    [InlineData("AdvancedHole2")]
    [InlineData("InsertMoveCopyBody2")]
    [InlineData("InsertStructuralWeldment5")]
    [InlineData("PreSplitBody2")]
    [InlineData("PostSplitBody2")]
    [InlineData("EditDeleteFace")]
    [InlineData("MoveOrCopy")]
    [InlineData("Paste")]
    public void TheFamiliesTheDecisionNamesAreRefused(string member)
    {
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member));
        Assert.Throws<MutatingCallError>(() => ReadOnlyCallGuard.Instance.Assert(member));
    }

    /// <summary>
    /// T169, the review of 2026-09-25: members of the four interfaces whose API help says they
    /// create something - a fillet corner feature, a scaled part, a named view, sketch relations,
    /// split sketch segments, a geodesic sketch offset, a selection set, a 3D View, the features a
    /// broken reference brings in - passed the guard bare, because the grammar does not reach them
    /// and rule 2 did not name them. Each is a named creator of its own interface, so the generated
    /// table, not this list, is what refuses it.
    /// </summary>
    [Theory]
    [InlineData("IFeatureManager", "FilletXpertMakeCorner")]
    [InlineData("IModelDoc2", "Scale")]
    [InlineData("IModelDoc2", "NameView")]
    [InlineData("IModelDoc2", "SkToolsAutoConstr")]
    [InlineData("IModelDoc2", "SplitOpenSegment")]
    [InlineData("IModelDoc2", "SplitClosedSegment")]
    [InlineData("IModelDocExtension", "GeodesicSketchOffset")]
    [InlineData("IModelDocExtension", "SaveSelection")]
    [InlineData("IModelDocExtension", "Capture3DView")]
    [InlineData("IModelDocExtension", "BreakAllExternalFileReferences2")]
    public void TheCreatorsTheReviewFoundAreNamedCreatorsOfTheirInterfaceAndRefused(string family, string member)
    {
        Assert.Contains(Named, row => Names(row, family, member));
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member));
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(family + "." + member));
    }

    /// <summary>
    /// The grammar's two matches that create nothing (T169): a box selection of the sketch entities
    /// already there, and the Add-In Manager. They stay refused - a denial fails closed, and allowing
    /// them would be a widening, which is the owner's call - and the contract says so beside rule 1,
    /// naming each by its interface, so its account of the grammar does not claim them as creators.
    /// </summary>
    [Theory]
    [InlineData("IModelDocExtension", "SketchBoxSelect")]
    [InlineData("IModelDoc2", "AddIns")]
    public void TheGrammarsTwoMatchesThatCreateNothingStayRefusedAndTheContractSaysSo(string family, string member)
    {
        Assert.Contains(Table, row => Names(row, family, member));
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member));
        Assert.Contains("`" + family + "." + member + "`", OverReachParagraph(), StringComparison.Ordinal);
    }

    /// <summary>The heading of rule 1's paragraph on the grammar's matches that create nothing.</summary>
    internal const string OverReachHeading = "**Two matches that create nothing**";

    /// <summary>Whether <paramref name="row"/> is <paramref name="family"/>'s and names <paramref name="member"/>.</summary>
    private static bool Names((string Family, string[] Members) row, string family, string member) =>
        DrawingFamilyDenylistTests.InterfaceOf(row) == family && row.Members.Contains(member, StringComparer.Ordinal);

    /// <summary>
    /// Rule 1's paragraph on the matches that create nothing, whitespace collapsed: from its heading
    /// to rule 2, which follows it.
    /// </summary>
    private static string OverReachParagraph()
    {
        string text = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, AllowlistFileName)).Replace("\r\n", "\n");
        int start = text.IndexOf(OverReachHeading, StringComparison.Ordinal);
        Assert.True(start >= 0, $"{Document} no longer carries the paragraph '{OverReachHeading}'.");
        int end = text.IndexOf("\n2. ", start, StringComparison.Ordinal);
        Assert.True(end > start, $"{Document}: the paragraph '{OverReachHeading}' is no longer followed by rule 2.");
        return Regex.Replace(text.Substring(start, end - start), @"\s+", " ");
    }

    /// <summary>
    /// The reads beside the creation family stay allowed, spelled as their call sites name them to the
    /// gate: the lookups and calculator factories the grammar reaches, and the tree and body reads it
    /// does not; and the selections beside the box selection the grammar refuses (T169), which are
    /// how the product selects.
    /// </summary>
    [Theory]
    [InlineData("FeatureById")]
    [InlineData("FeatureByName")]
    [InlineData("FeatureByPositionReverse")]
    [InlineData("FeatureFolderLocation")]
    [InlineData("CreateMassProperty")]
    [InlineData("CreateMassProperty2")]
    [InlineData("CreateMeasure")]
    [InlineData("FirstFeature")]
    [InlineData("GetNextFeature")]
    [InlineData("GetFeatureCount")]
    [InlineData("GetFeatures")]
    [InlineData("GetBodies2")]
    [InlineData("GetTypeName2")]
    [InlineData("GetEquationMgr")]
    [InlineData("IsNameUsed")]
    [InlineData("GetWhatsWrongCount")]
    [InlineData("SelectByID2")]
    [InlineData("SelectByRay")]
    [InlineData("MultiSelect2")]
    [InlineData("SelectAll")]
    public void TheReadsBesideThemStayAllowed(string member)
    {
        ReadOnlyGuard.Assert(member);
    }
}

/// <summary>
/// Decision 21A, T165. The tables are complete: the four interfaces are reflected on the interop the
/// extractor is built against, the creation grammar is applied, and every match is refused or is a
/// name the exclusion table states; every named creator is real and outside the grammar.
///
/// The grammar is written here a second time, beside the generator's copy, on purpose: this is the
/// independent check of the generator's output, and a verifier that reused the generator would agree
/// with any mistake it made. Both copies cite the contract's rule 1. Only metadata is read;
/// SOLIDWORKS is never started.
/// </summary>
public class CreationFamilyCompletenessTests
{
    /// <summary>The interfaces feature creation is reached through (the contract's decision 21A).</summary>
    internal static readonly string[] Families = { "IFeatureManager", "IModelDoc2", "IPartDoc", "IModelDocExtension" };

    /// <summary>Rule 1: the creation grammar, applied ordinally after the reader prefixes.</summary>
    private static readonly Regex CreationGrammar = new Regex(
        "^I?(Feature|Insert|Create|Add|Mirror|Make|Sketch|SimpleHole|SimpleFeature|HoleWizard|AdvancedHole)",
        RegexOptions.CultureInvariant);

    internal static bool IsCreation(string name) =>
        !DrawingFamilyCompletenessTests.IsReader(name) && CreationGrammar.IsMatch(name);

    private static HashSet<string> Declared(string family) =>
        new HashSet<string>(DrawingFamilyCompletenessTests.MethodNames(family), StringComparer.Ordinal);

    [RemodelInteropManifestTests.InteropAssembliesPresentFact]
    public void EveryFamilyOfTheDecisionIsOnTheInterop()
    {
        foreach (string family in Families)
        {
            DrawingFamilyCompletenessTests.InterfaceType(family);
        }
    }

    /// <summary>The heart of the decision: no creation member of the four is left callable by accident.</summary>
    [RemodelInteropManifestTests.InteropAssembliesPresentFact]
    public void EveryCreationMemberOfTheFamiliesIsRefusedOrANamedExclusion()
    {
        var excluded = new HashSet<string>(CreationFamilyDenylistTests.ExcludedMembers, StringComparer.OrdinalIgnoreCase);
        var callable = new List<string>();

        foreach (string family in Families)
        {
            foreach (string name in Declared(family).Where(IsCreation))
            {
                if (!excluded.Contains(name) && !GuardAnswers.ReadOnlyRefuses(name))
                {
                    callable.Add(family + "." + name);
                }
            }
        }

        Assert.True(
            callable.Count == 0,
            "Creation members of the four interfaces the guard does not refuse (regenerate the decision "
                + "21A tables with extractor/tools/list-creation-members.ps1): " + string.Join(", ", callable));
    }

    /// <summary>
    /// The other direction: each grammar row is one of the four interfaces, there is one row per
    /// interface, and every name a row denies is a grammar match declared on that interface, so nothing
    /// was typed into the generated table by hand.
    /// </summary>
    [RemodelInteropManifestTests.InteropAssembliesPresentFact]
    public void EveryGrammarRowNamesOnlyGrammarMatchesOfItsInterface()
    {
        Assert.Equal(
            Families.OrderBy(name => name, StringComparer.Ordinal),
            CreationFamilyDenylistTests.Table.Select(DrawingFamilyDenylistTests.InterfaceOf).OrderBy(name => name, StringComparer.Ordinal));

        foreach (var row in CreationFamilyDenylistTests.Table)
        {
            string family = DrawingFamilyDenylistTests.InterfaceOf(row);
            HashSet<string> declared = Declared(family);
            foreach (string member in row.Members)
            {
                Assert.True(declared.Contains(member), $"{family}.{member} is not declared on the interop.");
                Assert.True(IsCreation(member), $"{family}.{member} is not a creation member by the contract's rule 1.");
            }
        }
    }

    /// <summary>
    /// Rule 2: a named creator is declared on the interface its row names, is one of the four, and is
    /// outside the grammar - a named row the grammar already reaches would be padding.
    /// </summary>
    [RemodelInteropManifestTests.InteropAssembliesPresentFact]
    public void EveryNamedCreatorIsDeclaredOnItsInterfaceAndOutsideTheGrammar()
    {
        foreach (var row in CreationFamilyDenylistTests.Named)
        {
            string family = DrawingFamilyDenylistTests.InterfaceOf(row);
            Assert.Contains(family, Families);
            HashSet<string> declared = Declared(family);
            foreach (string member in row.Members)
            {
                Assert.True(declared.Contains(member), $"{family}.{member} is not declared on the interop.");
                Assert.False(IsCreation(member), $"{family}.{member} is a grammar match; rule 2 names only what rule 1 misses.");
            }
        }
    }

    /// <summary>
    /// Every exclusion is a grammar match declared on one of the four interfaces, so the "Not denied"
    /// table holds no stale name that would hide a later interop's writer of the same name.
    /// </summary>
    [RemodelInteropManifestTests.InteropAssembliesPresentFact]
    public void EveryExclusionIsACreationMatchOnTheFamilies()
    {
        var matches = new HashSet<string>(
            Families.SelectMany(Declared).Where(IsCreation), StringComparer.OrdinalIgnoreCase);

        foreach (string member in CreationFamilyDenylistTests.ExcludedMembers)
        {
            Assert.True(matches.Contains(member), $"{member} is excluded but matches no creation member of the four.");
        }
    }
}

/// <summary>
/// Decision 21A, T165. The denial refuses nothing the product calls through a read-only gate. Every
/// string literal of the product source is scanned, by the scan <see cref="DrawingFamilyReadAuditTests"/>
/// runs, and none may be refused by the decision 21A tables - with one exception: the throwaway-part
/// probe's own creation calls in <c>Rms/SwRemodelProbeHost.cs</c>, which <see cref="RemodelProbeGuard"/>
/// exempts (<see cref="ThrowawayPartExemptionTests"/>). The scan found, the day it was written,
/// <c>FeatureFillet3</c>, <c>InsertSketch</c> and <c>CreateCircleByRadius</c> there and nothing anywhere
/// else; the reads the grammar reaches (<c>CreateMassProperty2</c>, <c>CreateMeasure</c>,
/// <c>FeatureFolderLocation</c>) are the table's exclusions. Since T169 one literal that calls nothing
/// is named, as <see cref="DrawingFamilyReadAuditTests"/> names its own.
/// </summary>
public class CreationFamilyReadAuditTests
{
    /// <summary>The probe host's file: the only file whose literals may name a denied creation member.</summary>
    internal const string ProbeHostFile = "SwRemodelProbeHost.cs";

    /// <summary>
    /// Literals the scan finds that the tables refuse and that call nothing, each with where it is and
    /// why. Keyed case-insensitively, as the guard matches.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, string> NamedLiterals =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["scale"] = "Ir/DrawingSheet.cs: a JSON property name, matching IModelDoc2.Scale only by case (T169)",
        };

    private static bool IsTheProbesOwnCreationCall((string Literal, string Where) literal) =>
        literal.Where == ProbeHostFile
        && RemodelProbeGuard.ThrowawayPartCreationMembers.Contains(literal.Literal, StringComparer.OrdinalIgnoreCase);

    [Fact]
    public void NoLiteralOfTheProductSourceIsRefusedByTheTablesExceptTheProbesOwnCallsAndTheNamedOnes()
    {
        var table = new HashSet<string>(CreationFamilyDenylistTests.ExpectedMembers, StringComparer.OrdinalIgnoreCase);
        var refused = DrawingFamilyReadAuditTests.Literals()
            .Where(literal => table.Contains(DrawingFamilyReadAuditTests.Judged(literal.Literal)))
            .Where(literal => !IsTheProbesOwnCreationCall(literal) && !NamedLiterals.ContainsKey(literal.Literal))
            .Select(literal => $"\"{literal.Literal}\" in {literal.Where}")
            .Distinct(StringComparer.Ordinal)
            .ToList();

        Assert.True(
            refused.Count == 0,
            "The decision 21A denials refuse a name the product source uses; a read that needs a refused "
                + "member is a read that writes and is redesigned, never exempted: " + string.Join(", ", refused));
    }

    /// <summary>
    /// The exception is exercised, not vacuous: the probe host really names members the tables refuse,
    /// and each one it names is on <see cref="RemodelProbeGuard"/>'s exemption.
    /// </summary>
    [Fact]
    public void TheExceptionIsExercisedAndCoveredByTheProbesExemption()
    {
        var table = new HashSet<string>(CreationFamilyDenylistTests.ExpectedMembers, StringComparer.OrdinalIgnoreCase);
        var granted = DrawingFamilyReadAuditTests.Literals()
            .Where(literal => literal.Where == ProbeHostFile && table.Contains(literal.Literal))
            .Select(literal => literal.Literal)
            .Distinct(StringComparer.Ordinal)
            .ToList();

        Assert.NotEmpty(granted);
        Assert.All(granted, member => Assert.Contains(member, RemodelProbeGuard.ThrowawayPartCreationMembers, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Each named literal is still in the source and still refused by the tables, so the list cannot
    /// go stale and hide a later collision behind an entry nobody needs.
    /// </summary>
    [Fact]
    public void EveryNamedLiteralIsStillInTheSourceAndStillRefused() =>
        DrawingFamilyReadAuditTests.AssertEveryNamedLiteralIsStillInTheSourceAndRefused(
            NamedLiterals, CreationFamilyDenylistTests.ExpectedMembers);
}

/// <summary>
/// Decision 21A, T165. <see cref="RemodelProbeGuard"/>'s creation exemption is the throwaway part's and
/// holds nowhere else: it is exactly the creation members the probe host gates that
/// <see cref="ReadOnlyGuard"/> refuses; every other gate the product builds refuses each of them, bare
/// or qualified; the probe's own guard refuses their qualified spellings and every other member of the
/// tables; and the guard is built in exactly one place, <c>probe remodel</c>'s gate.
/// </summary>
public class ThrowawayPartExemptionTests
{
    /// <summary>The header of the contract's hand-kept exemption table.</summary>
    internal const string ExemptionHeader =
        "| Exempted for the throwaway part (decision 21A) | What the probe builds with it; what refuses it elsewhere |";

    /// <summary>The interfaces a qualified spelling is tried with: the four, and the sketch manager the probe calls.</summary>
    private static readonly string[] Interfaces = CreationFamilyCompletenessTests.Families.Concat(new[] { "ISketchManager" }).ToArray();

    public static readonly IReadOnlyList<(string Family, string[] Members)> ContractTable = DenylistTable.Parse(
        CreationFamilyDenylistTests.AllowlistFileName,
        CreationFamilyDenylistTests.Document + " throwaway-part exemption",
        ExemptionHeader,
        minimumRows: 5);

    /// <summary>The probe host's string literals that could name a member: a blank one names nothing.</summary>
    private static IEnumerable<string> ProbeHostLiterals() =>
        DrawingFamilyReadAuditTests.Literals()
            .Where(literal => literal.Where == CreationFamilyReadAuditTests.ProbeHostFile)
            .Select(literal => literal.Literal)
            .Where(literal => !string.IsNullOrWhiteSpace(literal))
            .Distinct(StringComparer.Ordinal);

    public static IEnumerable<object[]> EveryExemptedMember() =>
        RemodelProbeGuard.ThrowawayPartCreationMembers.OrderBy(member => member, StringComparer.Ordinal)
            .Select(member => new object[] { member });

    public static IEnumerable<object[]> EveryOtherMemberOfTheTables() =>
        CreationFamilyDenylistTests.ExpectedMembers
            .Except(RemodelProbeGuard.ThrowawayPartCreationMembers, StringComparer.OrdinalIgnoreCase)
            .OrderBy(member => member, StringComparer.Ordinal)
            .Select(member => new object[] { member });

    [Fact]
    public void TheContractsTableIsTheGuardsSet()
    {
        var contract = new HashSet<string>(ContractTable.SelectMany(row => row.Members), StringComparer.OrdinalIgnoreCase);

        Assert.True(
            contract.SetEquals(RemodelProbeGuard.ThrowawayPartCreationMembers),
            "The contract's throwaway-part exemption table and RemodelProbeGuard disagree. In the contract only: "
                + string.Join(", ", contract.Except(RemodelProbeGuard.ThrowawayPartCreationMembers, StringComparer.OrdinalIgnoreCase))
                + "; in the guard only: "
                + string.Join(", ", RemodelProbeGuard.ThrowawayPartCreationMembers.Except(contract, StringComparer.OrdinalIgnoreCase)) + ".");
    }

    /// <summary>
    /// Tied to the probe's scope: the exemption is the probe host's creation calls that the read-only
    /// guard refuses - no more (an entry the probe does not call would be a widening nobody uses) and no
    /// less (a call the guard refuses and the probe needs would fail at the seat).
    /// </summary>
    [Fact]
    public void TheExemptionIsExactlyTheProbeHostsCreationCallsTheReadOnlyGuardRefuses()
    {
        var expected = new HashSet<string>(
            ProbeHostLiterals().Where(literal => CreationFamilyCompletenessTests.IsCreation(literal) && GuardAnswers.ReadOnlyRefuses(literal)),
            StringComparer.OrdinalIgnoreCase);

        Assert.True(
            expected.SetEquals(RemodelProbeGuard.ThrowawayPartCreationMembers),
            "RemodelProbeGuard.ThrowawayPartCreationMembers is not the probe host's refused creation calls. "
                + "The host's: " + string.Join(", ", expected.OrderBy(member => member, StringComparer.Ordinal))
                + "; the guard's: " + string.Join(", ", RemodelProbeGuard.ThrowawayPartCreationMembers.OrderBy(member => member, StringComparer.Ordinal)) + ".");
    }

    /// <summary>The probe still works: every member its host gates that the read-only guard refuses, its own guard passes.</summary>
    [Fact]
    public void EveryProbeHostCallTheReadOnlyGuardRefusesPassesTheProbesGuard()
    {
        var guard = new RemodelProbeGuard();
        List<string> refused = ProbeHostLiterals().Where(GuardAnswers.ReadOnlyRefuses).ToList();

        Assert.Contains("FeatureFillet3", refused);
        foreach (string member in refused)
        {
            guard.Assert(member);
        }
    }

    [Theory]
    [MemberData(nameof(EveryExemptedMember))]
    public void NoOtherGateExemptsTheMemberBare(string member)
    {
        Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(member));
        foreach (ICallGuard gate in GuardAnswers.EveryGateTheProductBuilds().Where(gate => !(gate is RemodelProbeGuard)))
        {
            Assert.Throws<MutatingCallError>(() => gate.Assert(member));
        }
    }

    /// <summary>
    /// Qualified with any interface, every gate refuses an exempted member - the probe's own included -
    /// except the allowlist guard whose own key the qualified spelling is, which
    /// <see cref="TheOnlyAllowlistKeyAmongTheQualifiedSpellingsIsTheStage1Folder"/> pins.
    /// </summary>
    [Theory]
    [MemberData(nameof(EveryExemptedMember))]
    public void EveryGateRefusesTheMemberQualified(string member)
    {
        foreach (string key in Interfaces.Select(iface => CallKey.QualifiedKey(iface, member)))
        {
            Assert.Throws<MutatingCallError>(() => ReadOnlyGuard.Assert(key));
            foreach (ICallGuard gate in GuardAnswers.EveryGateTheProductBuilds())
            {
                if (GuardAnswers.AllowlistsByName(gate, key))
                {
                    gate.Assert(key);
                    continue;
                }

                Assert.Throws<MutatingCallError>(() => gate.Assert(key));
            }
        }
    }

    /// <summary>
    /// The one qualified spelling an allowlist accepts is the stage-1 folder key, a separate, reviewed
    /// entry of <see cref="RemodelGuard"/> (the re-modeler's one creation), not an exemption of the name.
    /// </summary>
    [Fact]
    public void TheOnlyAllowlistKeyAmongTheQualifiedSpellingsIsTheStage1Folder()
    {
        var allowlisted = RemodelProbeGuard.ThrowawayPartCreationMembers
            .SelectMany(member => Interfaces.Select(iface => CallKey.QualifiedKey(iface, member)))
            .Where(key => GuardAnswers.EveryGateTheProductBuilds().Any(gate => GuardAnswers.AllowlistsByName(gate, key)))
            .ToList();

        Assert.Equal(new[] { "IFeatureManager.InsertFeatureTreeFolder2" }, allowlisted);
        Assert.Contains("IFeatureManager.InsertFeatureTreeFolder2", RemodelGuard.AllowedKeys);
    }

    [Theory]
    [MemberData(nameof(EveryOtherMemberOfTheTables))]
    public void TheProbesGuardRefusesEveryOtherMemberOfTheTables(string member)
    {
        Assert.Throws<MutatingCallError>(() => new RemodelProbeGuard().Assert(member));
    }

    /// <summary>
    /// The exemption's scope is the one gate built with it: <c>Program.RemodelProbeGate</c>, which
    /// refuses to run while any document is open and addresses only the part it creates. A second
    /// construction site would carry the exemption to a gate the scope never reviewed.
    /// </summary>
    [Fact]
    public void TheProbesGuardIsBuiltInExactlyOnePlaceTheProbeGate()
    {
        var construction = new Regex(@"new\s+(?:[\w.]+\.)?RemodelProbeGuard\s*\(", RegexOptions.CultureInvariant);
        var sites = DrawingFamilyReadAuditTests.ProductSourceFiles()
            .SelectMany(file => construction.Matches(File.ReadAllText(file)).Cast<Match>().Select(match => Path.GetFileName(file)))
            .ToList();

        Assert.Equal(new[] { "Program.cs" }, sites);

        SwGate gate = SwReview.Extractor.Console.Program.RemodelProbeGate(new RecordingGateObserver());
        Assert.True(gate.Call("FeatureFillet3", () => true));
    }
}

/// <summary>The guard answers the decision 21A tests share.</summary>
internal static class GuardAnswers
{
    /// <summary>A fresh instance of every <see cref="ICallGuard"/> the product builds a gate with.</summary>
    public static IEnumerable<ICallGuard> EveryGateTheProductBuilds() => new ICallGuard[]
    {
        ReadOnlyCallGuard.Instance,
        new SuppressTestGuard(),
        new RemodelProbeGuard(),
        new RemodelGuard(),
        new DrawingOpenGuard(),
    };

    public static bool ReadOnlyRefuses(string member)
    {
        try
        {
            ReadOnlyGuard.Assert(member);
            return false;
        }
        catch (MutatingCallError)
        {
            return true;
        }
    }

    /// <summary>
    /// True when <paramref name="gate"/> is one of the two allowlist guards and <paramref name="key"/> is
    /// one of its own keys, which it accepts before <see cref="ReadOnlyGuard"/> is asked.
    /// </summary>
    public static bool AllowlistsByName(ICallGuard gate, string key) =>
        (gate is RemodelGuard && RemodelGuard.AllowedKeys.Contains(key))
        || (gate is DrawingOpenGuard && DrawingOpenGuard.AllowedKeys.Contains(key));
}
