"""What the standards goldens are for (T053 to T056, T069 to T070a).

`test_golden.py` pins every byte each fixture produces; this module pins the *claims* the
fixtures exist to make, so a baseline regenerated by hand cannot quietly accept a different
grading. Each test names the task and the success criterion it measures.

Every case runs exactly what the golden harness runs - the callable its own `case.json`
names, over its own `package.json` - so the two cannot drift apart.

**All sixteen checks are bound** since US2 (T066): `unavailable_checks` is empty on every
fixture here, and the four drawing checks grade the drawing a fixture carries rather than
reporting that nothing about them is claimed. On a fixture that carries no drawing they are
four `out_of_scope` rows - never skipped, and never absent.

A standards run grades **one** drawing: the root, when the root is a drawing
(`checks/standards/traversal.py`). So the five relationships T069 enumerates are five root
drawings and therefore five packages, held together as the case group
`fixtures/standards-drawings/` the way `fixtures/remodel-plan/` holds feature 004's.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from swreview.checks.standards.registry import RULES, STANDARDS_FAMILY
from swreview.checks.standards.traversal import part_number_matches
from swreview.ir.loader import load_package
from swreview.ir.models import EvidencePackage
from tests.checks.matched_pair import UNNUMBERED_PART
from tests.checks.standards_fixtures import fixture_profile
from tests.golden.test_golden import FIXTURES_DIR, resolve_callable

DRAWING_CHECKS: tuple[str, ...] = (
    "standards.drawing.dimensions_not_overridden",
    "standards.drawing.annotations_not_dangling",
    "standards.drawing.revision_matches",
    "standards.drawing.no_itar_statement",
)
"""The four checks US2 binds (T066)."""

DIMENSIONS, ANNOTATIONS, REVISION, NO_ITAR = DRAWING_CHECKS

DRAWINGS_GROUP = "standards-drawings"
"""T069's case group: one directory per root drawing, under one fixture directory."""

DRAWING_CASES: tuple[str, ...] = (
    "standards-drawings-seeded",
    "standards-drawings-compliant",
    "standards-drawings-ingested",
    "standards-drawings-two-models",
    "standards-drawings-no-views",
)
"""The five packages T069 enumerates, in the order the generator writes them.

One package each because a run grades the root drawing and no other: the seeded
three-sheet drawing, the compliant one, the one whose only sheet evidence is PDF-ingested,
the one whose views reference two models (one of which its own root also reaches), and the
one with no views at all.
"""

TRANSPARENCY = "standards.assembly.not_transparent"
MATE_REFERENCES = "standards.assembly.mate_references"
FULLY_MATED = "standards.assembly.fully_mated"
DATA_CARD = "standards.document.data_card_complete"

PART_CHECKS: tuple[str, ...] = tuple(
    check for check, rule in RULES.items() if rule.scope == "part"
)

UNREADABLE_SKETCH_PART = "MR-13005.SLDPRT"
UNREADABLE_MASS_PART = "MR-13004.SLDPRT"
"""The two parts `standards-unknown` seeds one unreadable signal each on (SC-003)."""

DRAWING_APPLICABLE: tuple[str, ...] = (*DRAWING_CHECKS, DATA_CARD)
"""The five checks a drawing document is graded by: its scope's four and the document one."""

MODEL_SCOPE_CHECKS: tuple[str, ...] = tuple(
    check for check, rule in RULES.items() if rule.scope in ("assembly", "document")
)
"""The seven assembly-scope checks and the one document-scope check.

The eight a sub-assembly document is graded by, which is what T056's counting rule is
asked of: reached twice, graded once.
"""

UNKNOWN_UNRESOLVED: frozenset[str] = frozenset(
    {
        MATE_REFERENCES,
        FULLY_MATED,
        TRANSPARENCY,
        "standards.part.sketches_fully_defined",
        "standards.part.material_assigned",
        "standards.part.rebuild_errors",
        "standards.part.cut_list_excluded",
        DATA_CARD,
        NO_ITAR,
    }
)
"""T055 and T070a: the nine checks `standards-unknown` leaves unresolved, named here.

Named rather than read back off the same run, because "the verdict lists what the coverage
rows say" is true of any set, the empty one included. The ninth is the drawing half T070a
adds: the fixture's drawing carries a note whose text could not be read, and an unread note
cannot be shown not to carry the export-control statement. The other three drawing ids are
absent because that drawing has nothing they cannot answer.
"""

SEEDED_FINDINGS: dict[str, int] = {
    "standards.assembly.not_exploded": 1,
    "standards.assembly.rebuild_errors": 1,
    "standards.assembly.mate_references": 1,
    "standards.assembly.one_fixed": 1,
    "standards.assembly.fully_mated": 1,
    "standards.assembly.not_hidden": 1,
    "standards.part.sketches_fully_defined": 1,
    "standards.part.rebuild_errors": 1,
    "standards.part.material_assigned": 1,
    "standards.part.cut_list_excluded": 1,
    "standards.document.data_card_complete": 1,
    DIMENSIONS: 1,
    ANNOTATIONS: 1,
    REVISION: 1,
    NO_ITAR: 1,
}
"""T053's second acceptance line (SC-001), deliverable now that T066 has landed: fifteen
findings, one per check except the transparency one, which is unresolved while
`TRANSPARENCY_POLARITY` is unsettled (SC-014)."""

SEEDED_ERRORS = 13
SEEDED_WARNINGS = 2
"""Eleven US1 errors plus the two error-severity drawing checks; the two warning-severity
drawing checks - `revision_matches` and `no_itar_statement` - are the warnings
(`contracts/rules.md`)."""


def graded(case_name: str) -> dict[str, Any]:
    """One golden case, run the way `test_golden.py` runs it."""
    directory = FIXTURES_DIR / case_name
    case = json.loads((directory / "case.json").read_text(encoding="utf-8"))
    function = resolve_callable(case["callable"])
    return function(load_package(directory).package, **case.get("kwargs", {}))


def package_of(case_name: str) -> EvidencePackage:
    return load_package(FIXTURES_DIR / case_name).package


def findings_by_check(result: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    by_check: dict[str, list[dict[str, Any]]] = {}
    for finding in result["findings"]:
        by_check.setdefault(finding["check"], []).append(finding)
    return by_check


def buckets_of(result: dict[str, Any], check: str) -> dict[str, list[str]]:
    """Which documents `check` landed in which bucket, off the coverage rows."""
    landed: dict[str, list[str]] = {}
    for row in result["coverage"]:
        if row["check"] != check:
            continue
        landed.setdefault(row["bucket"], []).extend(row["scope"]["document_ids"])
    return landed


def reasons_for(result: dict[str, Any], check: str, bucket: str) -> str:
    """Everything the coverage rows say about `check` in `bucket`, as one string."""
    return " ".join(
        row["reason"]
        for row in result["coverage"]
        if row["check"] == check and row["bucket"] == bucket
    )


def drawing_document(package: EvidencePackage) -> str:
    """The one drawing document of a package, which is the root of every T069 case."""
    drawings = [row.document_id for row in package.documents if row.kind == "drawing"]
    assert len(drawings) == 1, drawings
    return drawings[0]


def one_drawing_record(package: EvidencePackage) -> Any:
    """The one native drawing record of a package."""
    assert len(package.drawing_records) == 1, package.drawing_records
    return package.drawing_records[0]


def subject_names(result: dict[str, Any], finding: dict[str, Any]) -> list[str]:
    """The structured subjects of one finding, by name."""
    return [row["name"] for row in result["subjects"][finding["id"]]]


def rows_and_findings(result: dict[str, Any], check: str, document_id: str) -> int:
    """How many times `check` accounts for `document_id`: a coverage row or a finding.

    Exactly one is the answer a document graded once gives; two is a document graded
    twice, and none is the silent skip the hard rules forbid.
    """
    rows = [
        row
        for row in result["coverage"]
        if row["check"] == check and document_id in row["scope"]["document_ids"]
    ]
    findings = [
        finding
        for finding in result["findings"]
        if finding["check"] == check and document_of(finding) == document_id
    ]
    return len(rows) + len(findings)


def unresolved_checks(result: dict[str, Any]) -> set[str]:
    return {
        row["check"]
        for row in result["coverage"]
        if row["bucket"] == "unresolved" and row["check"] in RULES
    }


def document_of(finding: dict[str, Any]) -> str:
    return str(finding["provenance"][0]["document_id"])


def sub_assemblies(package: EvidencePackage) -> list[str]:
    """Every assembly below the top one, which is what difference h's rows name.

    The top assembly is the root document when a model was opened, and the one the root
    drawing's views reference when a drawing was: `design.root_assembly_document_id` holds
    the **drawing's** id for a drawing root, which is the feature 003 misnomer
    `contracts/ir-additions.md` section 7 keeps deliberately.
    """
    tops = {
        package.design.root_assembly_document_id,
        *(
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id is not None
        ),
    }
    return [
        row.document_id
        for row in package.documents
        if row.kind == "assembly" and row.document_id not in tops
    ]


def document_id_for(package: EvidencePackage, file_name: str) -> str:
    return next(row.document_id for row in package.documents if row.file_name == file_name)


def reached_only_through_unresolved_instances(package: EvidencePackage) -> set[str]:
    """Documents every instance of which is suppressed, lightweight or unloaded (FR-005)."""
    states: dict[str, set[str]] = {}
    for row in package.components:
        states.setdefault(row.document_id, set()).add(row.suppression)
    return {
        document_id
        for document_id, seen in states.items()
        if seen and "resolved" not in seen
    }


def full_paths_of(package: EvidencePackage, component_ids: list[str]) -> list[str]:
    """The occurrence path of each instance, in the order the finding named them.

    The finding shape T047 pins is id-only: `component_ids` and the `inputs` lines carry
    ids and the scope document, and neither they nor the `subjects` rows beside them carry
    `full_path`. So T056's "every path" is named *through* those ids, and this is what
    resolves them - a named id that no instance carries would raise here.
    """
    by_id = {row.id: row.full_path for row in package.components}
    return [by_id[component_id] for component_id in component_ids]


def shared_document_id(package: EvidencePackage) -> str:
    """The one assembly document two different parent instances both reach."""
    parents: dict[str, set[str | None]] = {}
    for row in package.components:
        parents.setdefault(row.document_id, set()).add(row.parent_id)
    assemblies = {row.document_id for row in package.documents if row.kind == "assembly"}
    shared = [
        document_id
        for document_id, seen in parents.items()
        if document_id in assemblies and len(seen) > 1
    ]
    assert len(shared) == 1, shared
    return shared[0]


@pytest.fixture(scope="module")
def seeded() -> dict[str, Any]:
    return graded("standards-seeded")


@pytest.fixture(scope="module")
def compliant() -> dict[str, Any]:
    return graded("standards-compliant")


@pytest.fixture(scope="module")
def flat() -> dict[str, Any]:
    return graded("standards-compliant-flat")


@pytest.fixture(scope="module")
def unknown() -> dict[str, Any]:
    return graded("standards-unknown")


@pytest.fixture(scope="module")
def multiplicity() -> dict[str, Any]:
    return graded("standards-multiplicity")


def drawing_case(name: str) -> str:
    """One T069 case, as `graded` and `package_of` name it inside the group."""
    assert name in DRAWING_CASES, name
    return f"{DRAWINGS_GROUP}/{name}"


@pytest.fixture(scope="module")
def drawings_seeded() -> dict[str, Any]:
    return graded(drawing_case("standards-drawings-seeded"))


@pytest.fixture(scope="module")
def drawings_compliant() -> dict[str, Any]:
    return graded(drawing_case("standards-drawings-compliant"))


@pytest.fixture(scope="module")
def drawings_ingested() -> dict[str, Any]:
    return graded(drawing_case("standards-drawings-ingested"))


@pytest.fixture(scope="module")
def drawings_two_models() -> dict[str, Any]:
    return graded(drawing_case("standards-drawings-two-models"))


@pytest.fixture(scope="module")
def drawings_no_views() -> dict[str, Any]:
    return graded(drawing_case("standards-drawings-no-views"))


# --- T053: standards-seeded ---------------------------------------------------------------


class TestSeeded:
    """One violation, in one document, of each of the sixteen checks (SC-001, SC-006)."""

    def test_each_check_but_the_transparency_one_produces_exactly_one_finding(
        self, seeded: dict[str, Any]
    ) -> None:
        counts = {check: len(rows) for check, rows in findings_by_check(seeded).items()}

        assert counts == SEEDED_FINDINGS

    def test_fifteen_findings_and_no_sixteenth(self, seeded: dict[str, Any]) -> None:
        """T053's second acceptance line, deliverable with T070 (SC-001)."""
        assert len(seeded["findings"]) == 15

    def test_the_transparency_check_is_one_unresolved_row_and_no_finding(
        self, seeded: dict[str, Any]
    ) -> None:
        landed = buckets_of(seeded, TRANSPARENCY)

        assert set(landed) - {"out_of_scope"} == {"unresolved"}
        assert len(landed["unresolved"]) == 1

    def test_no_seventeenth_check_result(self, seeded: dict[str, Any]) -> None:
        rows = [row["check"] for row in seeded["checks"]]

        assert rows == list(RULES)
        assert STANDARDS_FAMILY.summary_check not in rows

    def test_the_summary_item_is_present_and_is_not_counted_as_a_check(
        self, seeded: dict[str, Any]
    ) -> None:
        summaries = [
            row for row in seeded["coverage"] if row["check"] == STANDARDS_FAMILY.summary_check
        ]

        assert len(summaries) == 1
        assert STANDARDS_FAMILY.summary_check not in RULES

    def test_every_finding_carries_the_status_its_check_severity_maps_to(
        self, seeded: dict[str, Any]
    ) -> None:
        for finding in seeded["findings"]:
            rule = RULES[finding["check"]]
            expected = STANDARDS_FAMILY.status_by_severity[str(rule.severity)][0]
            assert finding["status"] == expected, finding["check"]

    def test_the_failing_part_is_reached_through_twenty_instances(
        self, seeded: dict[str, Any]
    ) -> None:
        """SC-006's first half: one finding per document, naming every instance."""
        part_findings = [
            finding
            for finding in seeded["findings"]
            if finding["check"].startswith("standards.part.")
        ]

        assert len(part_findings) == 4
        for finding in part_findings:
            assert len(finding["component_ids"]) == 20, finding["check"]

    def test_the_seeded_drawing_carries_six_overridden_dimensions(self) -> None:
        """SC-006's second half as the fixture seeds it; T070 grades it below."""
        package = package_of("standards-seeded")
        overridden = [
            dimension
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            for dimension in view.display_dimensions
            if dimension.is_overridden
        ]

        assert len(overridden) == 6
        assert len({dimension.view_id for dimension in overridden}) == 1

    def test_the_package_holds_exactly_one_assembly_document_and_one_drawing(self) -> None:
        """SC-001: a second assembly would add difference-h rows the counts exclude."""
        package = package_of("standards-seeded")
        assemblies = [row for row in package.documents if row.kind == "assembly"]
        drawings = [row for row in package.documents if row.kind == "drawing"]

        assert len(assemblies) == 1
        assert len(drawings) == 1

    def test_the_drawing_views_reference_that_same_root_assembly(self) -> None:
        package = package_of("standards-seeded")
        assembly = next(row.document_id for row in package.documents if row.kind == "assembly")
        referenced = {
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id is not None
        }

        assert referenced == {assembly}

    def test_two_violations_are_seeded_at_depth(self, seeded: dict[str, Any]) -> None:
        """Difference z: a defect inside a folder or a derived feature is still a subject."""
        package = package_of("standards-seeded")
        nested = {row.id for row in package.features if row.folder_id is not None}
        by_check = findings_by_check(seeded)

        for check in ("standards.part.sketches_fully_defined", "standards.part.rebuild_errors"):
            named = {entry.split()[1] for entry in by_check[check][0]["inputs"]}
            assert named & nested, check

    def test_no_check_is_unavailable_now_that_the_drawing_evaluators_are_bound(
        self, seeded: dict[str, Any]
    ) -> None:
        """T066 emptied the list; a check that fell out of the dispatch would refill it."""
        assert seeded["unavailable_checks"] == []

    def test_the_six_overridden_dimensions_are_one_finding_naming_all_six(
        self, seeded: dict[str, Any]
    ) -> None:
        """SC-006's drawing half (T070): six subjects inside one finding, not six findings."""
        drawing_id = drawing_document(package_of("standards-seeded"))
        findings = findings_by_check(seeded)[DIMENSIONS]

        assert len(findings) == 1
        assert document_of(findings[0]) == drawing_id
        assert len(subject_names(seeded, findings[0])) == 6
        assert len(findings[0]["inputs"]) == 6

    def test_that_one_finding_contributes_one_to_the_error_count(
        self, seeded: dict[str, Any]
    ) -> None:
        """The counting rule measured: the error count moves by one, not by six."""
        errors = [
            finding
            for finding in seeded["findings"]
            if RULES[finding["check"]].severity == "error"
        ]

        assert seeded["verdict"]["counts"]["error"] == len(errors) == SEEDED_ERRORS
        assert len([finding for finding in errors if finding["check"] == DIMENSIONS]) == 1

    def test_the_verdict_is_not_ready_and_carries_the_unresolved_ids(
        self, seeded: dict[str, Any]
    ) -> None:
        verdict = seeded["verdict"]

        assert verdict["state"] == "not_ready"
        assert verdict["counts"]["error"] == SEEDED_ERRORS
        assert verdict["counts"]["warning"] == SEEDED_WARNINGS
        assert TRANSPARENCY in verdict["unresolved_check_ids"]


# --- T054: standards-compliant and standards-compliant-flat -------------------------------


class TestCompliant:
    """SC-002's model half: zero findings, and what `ready` costs."""

    def test_the_multi_level_fixture_produces_zero_findings(
        self, compliant: dict[str, Any]
    ) -> None:
        assert compliant["findings"] == []

    def test_the_multi_level_fixture_carries_parts_sub_assemblies_and_a_drawing(self) -> None:
        package = package_of("standards-compliant")
        kinds = {row.kind for row in package.documents}

        assert kinds == {"part", "assembly", "drawing"}
        assert sub_assemblies(package)

    @pytest.mark.parametrize(
        ("case", "known_gaps"),
        [
            ("compliant", frozenset({MATE_REFERENCES, FULLY_MATED, TRANSPARENCY})),
            ("flat", frozenset({TRANSPARENCY})),
        ],
    )
    def test_every_check_is_checked_or_skipped_with_a_stated_reason(
        self,
        case: str,
        known_gaps: frozenset[str],
        request: pytest.FixtureRequest,
    ) -> None:
        """T054's acceptance line and T069a's, asked of **both** compliant fixtures.

        `standards-compliant-flat` is the one the Phase 3 Independent Test names - the
        single-level fixture of spec.md:21 - so the assertion has to be made there too: a
        check that emitted no coverage row at all for that package would be the silent
        skip the hard rules forbid, and `findings == []` cannot see it. The flat fixture
        has no sub-assembly, so the two difference-h gaps do not arise there and only the
        unsettled transparency polarity is left unresolved.

        **All sixteen** since T069a: the four drawing checks grade the drawing each of
        these fixtures carries rather than reporting that this build does not run them.
        """
        result: dict[str, Any] = request.getfixturevalue(case)
        assert len(RULES) == 16
        for check in RULES:
            landed = buckets_of(result, check)
            assert landed, check
            graded_buckets = set(landed) - {"out_of_scope"}
            if check in known_gaps:
                assert "unresolved" in graded_buckets, check
            else:
                assert graded_buckets <= {"checked", "skipped"}, check
        for row in result["coverage"]:
            assert row["reason"], row["check"]

    def test_the_two_known_gaps_name_each_sub_assembly(self, compliant: dict[str, Any]) -> None:
        subs = sub_assemblies(package_of("standards-compliant"))

        assert subs
        assert buckets_of(compliant, MATE_REFERENCES)["unresolved"] == subs
        assert buckets_of(compliant, FULLY_MATED)["unresolved"] == subs

    def test_the_unresolved_ids_are_the_two_known_gaps_and_the_polarity(
        self, compliant: dict[str, Any]
    ) -> None:
        """T069a: with the drawing evaluators bound, nothing else is left unresolved."""
        expected = {MATE_REFERENCES, FULLY_MATED, TRANSPARENCY}

        assert unresolved_checks(compliant) == expected
        assert set(compliant["verdict"]["unresolved_check_ids"]) == expected

    @pytest.mark.parametrize(
        "case", ["standards-compliant", "standards-compliant-flat"]
    )
    def test_every_drawing_check_grades_the_drawing_of_both_compliant_fixtures(
        self, case: str, request: pytest.FixtureRequest
    ) -> None:
        """T069a's drawing half: checked or skipped on the drawing, never unresolved."""
        result: dict[str, Any] = request.getfixturevalue(
            "compliant" if case == "standards-compliant" else "flat"
        )
        drawing_id = drawing_document(package_of(case))
        for check in DRAWING_APPLICABLE:
            reached = {
                bucket
                for bucket, ids in buckets_of(result, check).items()
                if drawing_id in ids
            }
            assert reached, (case, check)
            assert reached <= {"checked", "skipped"}, (case, check, reached)

    def test_no_check_is_unavailable_on_either_compliant_fixture(
        self, compliant: dict[str, Any], flat: dict[str, Any]
    ) -> None:
        assert compliant["unavailable_checks"] == []
        assert flat["unavailable_checks"] == []

    def test_the_multi_level_verdict_is_ready_coverage_incomplete(
        self, compliant: dict[str, Any]
    ) -> None:
        assert compliant["verdict"]["state"] == "ready_coverage_incomplete"
        assert compliant["verdict"]["counts"]["error"] == 0

    def test_the_flat_fixture_produces_zero_findings(self, flat: dict[str, Any]) -> None:
        assert flat["findings"] == []

    def test_the_flat_fixture_has_no_sub_assembly_and_one_drawing(self) -> None:
        package = package_of("standards-compliant-flat")
        drawings = [row for row in package.documents if row.kind == "drawing"]

        assert sub_assemblies(package) == []
        assert len(drawings) == 1

    def test_the_flat_fixture_is_unresolved_only_where_this_build_cannot_answer(
        self, flat: dict[str, Any]
    ) -> None:
        """T069a: the polarity is the **only** unresolved id left; SC-014 then gives `ready`."""
        assert unresolved_checks(flat) == {TRANSPARENCY}
        assert flat["verdict"]["state"] == "ready_coverage_incomplete"

    def test_the_flat_headline_carries_no_no_drawing_note(self, flat: dict[str, Any]) -> None:
        assert "no drawing graded" not in flat["verdict"]["notes"]

    def test_every_compliant_drawing_sheet_records_a_sheet_format_view(self) -> None:
        """Without a type-1 view per sheet `no_itar_statement` can never reach `ready`."""
        for case in ("standards-compliant", "standards-compliant-flat"):
            for record in package_of(case).drawing_records:
                for sheet in record.sheets:
                    assert any(view.view_type_raw == 1 for view in sheet.views), sheet.name


# --- T055: standards-unknown (model half) -------------------------------------------------


class TestUnknown:
    """SC-003's model half: unknown stays unknown, and never becomes a pass."""

    def test_the_fixture_is_otherwise_compliant(self, unknown: dict[str, Any]) -> None:
        assert unknown["verdict"]["counts"]["error"] == 0
        assert unknown["findings"] == []

    def test_the_verdict_is_ready_coverage_incomplete_naming_the_unresolved_ids(
        self, unknown: dict[str, Any]
    ) -> None:
        assert unknown["verdict"]["state"] == "ready_coverage_incomplete"
        assert unresolved_checks(unknown) == UNKNOWN_UNRESOLVED
        assert set(unknown["verdict"]["unresolved_check_ids"]) == UNKNOWN_UNRESOLVED

    def test_the_suppressed_and_lightweight_components_are_skipped_with_their_state(
        self, unknown: dict[str, Any]
    ) -> None:
        for check in (
            "standards.assembly.one_fixed",
            "standards.assembly.fully_mated",
            "standards.assembly.not_hidden",
        ):
            reasons = " ".join(
                row["reason"]
                for row in unknown["coverage"]
                if row["check"] == check and row["bucket"] == "skipped"
            )
            assert "suppressed" in reasons, check
            assert "lightweight" in reasons, check

    def test_the_unreadable_sketch_status_is_unresolved_and_that_part_is_not_checked(
        self, unknown: dict[str, Any]
    ) -> None:
        check = "standards.part.sketches_fully_defined"
        part = document_id_for(package_of("standards-unknown"), UNREADABLE_SKETCH_PART)
        landed = buckets_of(unknown, check)
        reasons = [
            row["reason"]
            for row in unknown["coverage"]
            if row["check"] == check and row["bucket"] == "unresolved"
        ]

        assert part in landed["unresolved"]
        assert part not in landed.get("checked", ())
        assert any("constrained status is unavailable" in reason for reason in reasons)

    def test_the_unreadable_mass_override_is_unresolved_and_that_part_is_not_checked(
        self, unknown: dict[str, Any]
    ) -> None:
        check = "standards.part.material_assigned"
        part = document_id_for(package_of("standards-unknown"), UNREADABLE_MASS_PART)
        landed = buckets_of(unknown, check)
        reasons = [
            row["reason"]
            for row in unknown["coverage"]
            if row["check"] == check and row["bucket"] == "unresolved"
        ]

        assert part in landed["unresolved"]
        assert part not in landed.get("checked", ())
        assert any("whether the mass is overridden was not read" in reason for reason in reasons)

    def test_a_document_reached_only_through_unresolved_instances_is_never_graded(
        self, unknown: dict[str, Any]
    ) -> None:
        """FR-005: what the package records about it is not a reading of that document."""
        blocked = reached_only_through_unresolved_instances(package_of("standards-unknown"))

        assert len(blocked) == 2
        for check in (*PART_CHECKS, DATA_CARD):
            landed = buckets_of(unknown, check)
            assert blocked <= set(landed.get("unresolved", ())), check
            assert not blocked & set(landed.get("checked", ())), check
            assert not blocked & set(landed.get("skipped", ())), check

    def test_the_sub_assembly_is_what_the_mate_check_cannot_answer_for(
        self, unknown: dict[str, Any]
    ) -> None:
        subs = sub_assemblies(package_of("standards-unknown"))

        assert subs
        assert buckets_of(unknown, MATE_REFERENCES)["unresolved"] == subs

    def test_the_unread_note_leaves_the_export_control_check_unresolved(
        self, unknown: dict[str, Any]
    ) -> None:
        """T070a: an unread note cannot be shown not to carry the statement (FR-021)."""
        drawing_id = drawing_document(package_of("standards-unknown"))
        landed = buckets_of(unknown, NO_ITAR)
        reasons = reasons_for(unknown, NO_ITAR, "unresolved")

        assert landed.get("unresolved") == [drawing_id]
        assert "checked" not in landed
        assert "its text was not read" in reasons
        assert "note_text" in reasons

    def test_the_unread_note_is_a_gap_and_not_an_empty_string(self) -> None:
        """The fixture's own claim: null text with the `note_text` gap beside it."""
        package = package_of("standards-unknown")
        notes = [
            note
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            for note in view.notes
        ]
        unread = [note for note in notes if note.text is None]

        assert len(unread) == 1
        assert [gap.entity_id for gap in package.gaps if gap.entity_kind == "note_text"] == [
            unread[0].id
        ]

    def test_every_sheet_of_the_unknown_drawing_records_a_sheet_format_view(self) -> None:
        """Otherwise the unresolved row would come from the missing pseudo-view."""
        for record in package_of("standards-unknown").drawing_records:
            for sheet in record.sheets:
                assert any(view.view_type_raw == 1 for view in sheet.views), sheet.name

    def test_no_drawing_check_passes_or_fails_on_the_unread_note(
        self, unknown: dict[str, Any]
    ) -> None:
        """The other three drawing checks are answerable and answered; none fails."""
        drawing_id = drawing_document(package_of("standards-unknown"))
        for check in DRAWING_CHECKS:
            reached = {
                bucket
                for bucket, ids in buckets_of(unknown, check).items()
                if drawing_id in ids
            }
            assert "failed" not in reached, check
            if check == NO_ITAR:
                assert reached == {"unresolved"}
            else:
                assert reached <= {"checked", "skipped"}, (check, reached)

    def test_the_unknown_headline_carries_no_no_drawing_note(
        self, unknown: dict[str, Any]
    ) -> None:
        """The fixture carries a drawing now, so the note must be gone (T070a)."""
        assert "no drawing graded" not in unknown["verdict"]["notes"]


# --- T056: standards-multiplicity ---------------------------------------------------------


class TestMultiplicity:
    """SC-006's counting rule: per document, not per instance, parent or subject."""

    def test_one_sub_assembly_appears_under_two_parents(self) -> None:
        package = package_of("standards-multiplicity")
        shared = [
            row for row in package.components if row.document_id == shared_document_id(package)
        ]

        assert len(shared) == 2
        assert len({row.parent_id for row in shared}) == 2

    def test_each_failing_check_produces_exactly_one_finding_per_document(
        self, multiplicity: dict[str, Any]
    ) -> None:
        pairs = [
            (finding["check"], document_of(finding)) for finding in multiplicity["findings"]
        ]

        assert len(pairs) == len(set(pairs))

    def test_the_error_count_equals_the_number_of_distinct_failing_pairs(
        self, multiplicity: dict[str, Any]
    ) -> None:
        pairs = {(finding["check"], document_of(finding)) for finding in multiplicity["findings"]}

        assert multiplicity["verdict"]["counts"]["error"] == len(pairs)
        assert len(pairs) == 4

    def test_the_shared_sub_assembly_gets_one_set_of_rows_naming_both_instances(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")
        shared = shared_document_id(package)
        instances = [row.id for row in package.components if row.document_id == shared]
        findings = [
            finding for finding in multiplicity["findings"] if document_of(finding) == shared
        ]

        assert len(findings) == 3
        for finding in findings:
            assert finding["component_ids"] == instances, finding["check"]

    def test_the_shared_sub_assembly_is_accounted_for_once_per_check_and_not_twice(
        self, multiplicity: dict[str, Any]
    ) -> None:
        """T056's "one set of rows and not two", measured on the rows and not the findings.

        Reached twice, graded once: for each of the eight checks whose scope a sub-assembly
        document matches, the shared document is named by exactly one coverage row **or**
        by exactly one finding - never by two rows, never by a row and a finding both, and
        never by none, which would be the silent skip the hard rules forbid.
        """
        shared = shared_document_id(package_of("standards-multiplicity"))

        assert len(MODEL_SCOPE_CHECKS) == 8
        for check in MODEL_SCOPE_CHECKS:
            rows = [
                row
                for row in multiplicity["coverage"]
                if row["check"] == check and shared in row["scope"]["document_ids"]
            ]
            findings = [
                finding
                for finding in multiplicity["findings"]
                if finding["check"] == check and document_of(finding) == shared
            ]
            assert len(rows) + len(findings) == 1, (check, rows, findings)

    def test_the_shared_sub_assembly_s_findings_name_both_occurrence_paths(
        self, multiplicity: dict[str, Any]
    ) -> None:
        """T056's "every path": the ids each finding names resolve to the two occurrences.

        `MR-40004` is reached once under `MR-40002` and once under `MR-40003`, and an
        engineer reading `cmp:0004` and `cmp:0009` has to be able to tell which two
        occurrences those are. The finding shape T047 pins is id-only, so the paths are
        named through the ids (see `full_paths_of`) rather than carried beside them - if
        that changes, this is the assertion to move onto whatever field carries them.
        """
        package = package_of("standards-multiplicity")
        shared = shared_document_id(package)
        findings = [
            finding for finding in multiplicity["findings"] if document_of(finding) == shared
        ]

        assert findings
        for finding in findings:
            paths = full_paths_of(package, finding["component_ids"])
            parents = {path.rsplit("/", 1)[0] for path in paths}
            assert len(paths) == 2, finding["check"]
            assert len(set(paths)) == 2, (finding["check"], paths)
            assert len(parents) == 2, (finding["check"], paths)

    def test_the_many_times_used_part_gets_one_finding_naming_every_instance(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")
        findings = [
            finding
            for finding in multiplicity["findings"]
            if finding["check"] == "standards.part.material_assigned"
        ]

        assert len(findings) == 1
        instances = [
            row.id for row in package.components if row.document_id == document_of(findings[0])
        ]
        assert len(instances) == 8
        assert findings[0]["component_ids"] == instances
        paths = full_paths_of(package, findings[0]["component_ids"])
        assert len(set(paths)) == 8, paths
        assert len({path.rsplit("/", 1)[0] for path in paths}) == 2, paths

    def test_the_fixture_carries_no_drawing_and_its_drawing_rows_are_out_of_scope(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")

        assert not [row for row in package.documents if row.kind == "drawing"]
        for check in DRAWING_CHECKS:
            assert set(buckets_of(multiplicity, check)) == {"out_of_scope"}, check


# --- T069: the standards-drawings case group ----------------------------------------------


class TestDrawings:
    """SC-007: every sheet read, every relationship a drawing can be in (T069).

    Five root drawings, so five packages: a run grades the drawing that was opened and no
    other, so "a second, compliant drawing in the same fixture" is a second package in the
    same case group rather than a second document in one.
    """

    def test_the_group_holds_one_case_per_relationship(self) -> None:
        directory = FIXTURES_DIR / DRAWINGS_GROUP
        cases = sorted(
            path.name
            for path in directory.iterdir()
            if path.is_dir() and path.name != "__pycache__"
        )

        assert cases == sorted(DRAWING_CASES)
        for case in DRAWING_CASES:
            assert (directory / case / "case.json").is_file(), case

    # --- the seeded three-sheet drawing ---------------------------------------------------

    def test_the_seeded_drawing_carries_three_sheets_with_the_table_off_the_first(
        self,
    ) -> None:
        """T069's shape: three sheets, and a revision table on a sheet other than sheet 1."""
        record = one_drawing_record(package_of(drawing_case("standards-drawings-seeded")))
        with_tables = [sheet.index for sheet in record.sheets if sheet.revision_tables]

        assert [sheet.name for sheet in record.sheets] == ["Sheet1", "Sheet2", "Sheet3"]
        assert with_tables == [1]

    def test_each_drawing_check_finds_its_seeded_violation(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        """Four findings on the drawing, one per drawing check, and no fifth."""
        drawing_id = drawing_document(package_of(drawing_case("standards-drawings-seeded")))
        by_check = findings_by_check(drawings_seeded)

        assert {check: len(rows) for check, rows in by_check.items()} == dict.fromkeys(
            DRAWING_CHECKS, 1
        )
        for finding in drawings_seeded["findings"]:
            assert document_of(finding) == drawing_id, finding["check"]

    def test_every_seeded_violation_is_found_on_the_sheet_it_sits_on(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        """Difference q: every sheet is read, not only the active one."""
        by_check = findings_by_check(drawings_seeded)

        assert "sheet 'Sheet1'" in by_check[DIMENSIONS][0]["observed"]
        assert "sheet 'Sheet2'" in by_check[ANNOTATIONS][0]["observed"]
        assert "sheet 'Sheet2'" in by_check[REVISION][0]["observed"]
        assert "sheet 'Sheet3'" in by_check[NO_ITAR][0]["observed"]

    def test_the_overridden_dimension_is_rendered_with_the_unit_it_was_recorded_in(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        """Difference p: never a bare number, and never a guessed unit."""
        observed = findings_by_check(drawings_seeded)[DIMENSIONS][0]["observed"]

        assert "99.5 mm" in observed
        assert "12.5 mm" in observed

    def test_the_revision_warning_names_the_table_reading_and_the_property(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        observed = findings_by_check(drawings_seeded)[REVISION][0]["observed"]

        assert "'AC'" in observed
        assert "'AB'" in observed
        assert "row 0 from the end, column 1" in observed

    def test_every_drawing_subject_names_its_sheet_its_view_and_its_identity(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        """Difference o: an entity is located, and is a subject even when it has no name."""
        for finding in drawings_seeded["findings"]:
            if finding["check"] == REVISION:
                continue  # its one subject is the drawing document itself
            for name in subject_names(drawings_seeded, finding):
                assert len(name.split("/")) == 3, (finding["check"], name)

    def test_the_severities_are_two_errors_and_two_warnings(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        counts = drawings_seeded["verdict"]["counts"]

        assert (counts["error"], counts["warning"]) == (2, 2)
        assert drawings_seeded["verdict"]["state"] == "not_ready"

    def test_the_document_check_grades_the_seeded_drawing_too(
        self, drawings_seeded: dict[str, Any]
    ) -> None:
        """The fifth drawing-applicable check: its data card is complete, so it is checked."""
        drawing_id = drawing_document(package_of(drawing_case("standards-drawings-seeded")))

        assert drawing_id in buckets_of(drawings_seeded, DATA_CARD)["checked"]

    # --- the compliant drawing ------------------------------------------------------------

    def test_the_compliant_drawing_yields_five_checked_rows_and_zero_findings(
        self, drawings_compliant: dict[str, Any]
    ) -> None:
        drawing_id = drawing_document(
            package_of(drawing_case("standards-drawings-compliant"))
        )
        checked = [
            check
            for check in DRAWING_APPLICABLE
            if drawing_id in buckets_of(drawings_compliant, check).get("checked", ())
        ]

        assert drawings_compliant["findings"] == []
        assert checked == list(DRAWING_APPLICABLE)
        assert len(checked) == 5

    def test_the_compliant_drawing_s_file_name_follows_the_part_number_pattern(self) -> None:
        package = package_of(drawing_case("standards-drawings-compliant"))
        drawing = next(row for row in package.documents if row.kind == "drawing")

        assert part_number_matches(fixture_profile().part_number.pattern, drawing.file_name)

    def test_the_compliant_drawing_s_referenced_model_carries_the_same_revision(self) -> None:
        profile = fixture_profile()
        package = package_of(drawing_case("standards-drawings-compliant"))
        revisions = {
            row.file_name: row.custom_properties.get(profile.revision.property)
            for row in package.documents
        }

        assert len(set(revisions.values())) == 1
        assert set(revisions.values()) == {profile.revision.initial}

    # --- the PDF-ingested drawing ---------------------------------------------------------

    def test_the_pdf_ingested_drawing_carries_no_native_sheet(self) -> None:
        package = package_of(drawing_case("standards-drawings-ingested"))

        assert one_drawing_record(package).sheets == []
        assert [sheet.source for sheet in package.drawings] == ["pdf_ingest"]

    def test_every_drawing_check_is_unresolved_naming_the_evidence_source(
        self, drawings_ingested: dict[str, Any]
    ) -> None:
        """FR-024: a parser with known limits may not produce a demonstrated finding."""
        drawing_id = drawing_document(package_of(drawing_case("standards-drawings-ingested")))
        for check in DRAWING_CHECKS:
            landed = buckets_of(drawings_ingested, check)
            reasons = reasons_for(drawings_ingested, check, "unresolved")

            assert landed.get("unresolved") == [drawing_id], check
            assert set(landed) - {"out_of_scope"} == {"unresolved"}, check
            assert "no natively dumped sheet" in reasons, check
            assert "pdf_ingest" in reasons, check

        assert drawings_ingested["findings"] == []

    # --- the two-model drawing, and the document two paths reach --------------------------

    def test_both_referenced_models_are_graded(
        self, drawings_two_models: dict[str, Any]
    ) -> None:
        package = package_of(drawing_case("standards-drawings-two-models"))
        referenced = {
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id is not None
        }

        assert len(referenced) == 2
        assert referenced <= set(drawings_two_models["documents"])

    def test_both_revision_disagreements_are_named_in_the_one_warning(
        self, drawings_two_models: dict[str, Any]
    ) -> None:
        """One finding per drawing, naming every disagreement it found (FR-020)."""
        package = package_of(drawing_case("standards-drawings-two-models"))
        findings = findings_by_check(drawings_two_models)[REVISION]
        models = [
            row.file_name
            for row in package.documents
            if row.kind in ("assembly", "part")
            and row.document_id
            in {
                view.referenced_document_id
                for record in package.drawing_records
                for sheet in record.sheets
                for view in sheet.views
            }
        ]

        assert len(findings) == 1
        assert len(models) == 2
        for file_name in models:
            assert file_name in findings[0]["observed"], file_name

    def test_the_doubly_reached_document_is_graded_once(
        self, drawings_two_models: dict[str, Any]
    ) -> None:
        """FR-003: reached from a view and again through the assembly's tree, graded once."""
        package = package_of(drawing_case("standards-drawings-two-models"))
        shared = next(
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id
            in {row.document_id for row in package.documents if row.kind == "part"}
        )
        instances = [row for row in package.components if row.document_id == shared]

        assert instances, "the shared part must also hang in the assembly's tree"
        assert drawings_two_models["documents"].count(shared) == 1
        for check in PART_CHECKS:
            assert rows_and_findings(drawings_two_models, check, shared) == 1, check

    # --- the drawing with no views ---------------------------------------------------------

    def test_the_no_views_drawing_still_runs_its_own_checks(
        self, drawings_no_views: dict[str, Any]
    ) -> None:
        """Difference f: nothing crashes, and the checks that can answer do."""
        drawing_id = drawing_document(package_of(drawing_case("standards-drawings-no-views")))

        assert drawings_no_views["findings"] == []
        for check in (DIMENSIONS, ANNOTATIONS):
            assert buckets_of(drawings_no_views, check).get("skipped") == [drawing_id], check

    def test_the_model_comparison_is_unresolved_naming_the_missing_reference(
        self, drawings_no_views: dict[str, Any]
    ) -> None:
        reasons = reasons_for(drawings_no_views, REVISION, "unresolved")

        assert "references no document" in reasons
        assert "its own revision table was compared" in reasons

    def test_the_no_views_drawing_records_sheets_and_no_view_at_all(self) -> None:
        record = one_drawing_record(package_of(drawing_case("standards-drawings-no-views")))

        assert record.sheets
        assert [view for sheet in record.sheets for view in sheet.views] == []

    # --- every case, and the catalogue -----------------------------------------------------

    @pytest.mark.parametrize("case", DRAWING_CASES)
    def test_every_case_grades_exactly_one_drawing_and_leaves_no_check_unavailable(
        self, case: str
    ) -> None:
        result = graded(drawing_case(case))
        package = package_of(drawing_case(case))
        drawing_id = drawing_document(package)

        assert result["document_kinds"][drawing_id] == "drawing"
        assert result["unavailable_checks"] == []
        assert "no drawing graded" not in result["verdict"]["notes"]


# --- T098: standards-profile-a and standards-profile-b -------------------------------------


MATCHED_PAIR: dict[str, str] = {
    "standards-profile-a": "profile-a",
    "standards-profile-b": "profile-b",
}
"""SC-005's third measurement: one design written twice, once for each fictional profile.

The packages differ in every string a profile decides - the vault root, the library folders,
the file names, the data-card property names, the material configuration, the revision
property and the export-control phrase - and in nothing else. Graded each against its own
profile they must agree, and a value compiled into the source cannot make them
(`tests/checks/matched_pair.py`).
"""

PAIR_A, PAIR_B = MATCHED_PAIR

MATERIAL_ASSIGNED = "standards.part.material_assigned"


def graded_against(case_name: str, profile: str) -> dict[str, Any]:
    """One golden case, graded against `profile` rather than the one its `case.json` names.

    The cross grading is the control the equality below needs: two packages graded by a
    reviewer that ignored the profile entirely would agree just as well, so the pair is only
    evidence if grading a package against the *other* profile changes what it says.
    """
    directory = FIXTURES_DIR / case_name
    case = json.loads((directory / "case.json").read_text(encoding="utf-8"))
    function = resolve_callable(case["callable"])
    return function(load_package(directory).package, profile=profile)


def coverage_shape(result: dict[str, Any]) -> list[tuple[str, str, tuple[str, ...]]]:
    """Every coverage row as `(bucket, check, documents)`, ordered and profile-free.

    The rows' **reasons** are deliberately not compared: a reason names the matched prefix,
    the property or the configuration the profile supplied, so two runs against two profiles
    that differ in every field cannot carry the same reason text and should not be asked to.
    What must be identical is where every check landed, over which documents.
    """
    return sorted(
        (row["bucket"], row["check"], tuple(sorted(row["scope"]["document_ids"])))
        for row in result["coverage"]
    )


def findings_shape(result: dict[str, Any]) -> list[tuple[str, str, str, int, tuple[str, ...]]]:
    """Every finding as `(check, status, severity, subjects, components)`."""
    return sorted(
        (
            finding["check"],
            finding["status"],
            finding["severity"],
            len(result["subjects"][finding["id"]]),
            tuple(sorted(finding["component_ids"])),
        )
        for finding in result["findings"]
    )


def profile_strings(case_name: str) -> set[str]:
    """Every document path, file name and custom-property name the package carries.

    The pair is only a pair if these differ: two packages written for one profile would
    agree trivially, and the whole measurement would be vacuous.
    """
    package = package_of(case_name)
    strings = {row.path for row in package.documents if row.path}
    strings |= {row.file_name for row in package.documents if row.file_name}
    for row in package.documents:
        strings |= set(row.custom_properties)
    return strings


class TestTheMatchedPair:
    """T098, quickstart Scenario 6: no company value is compiled in (SC-005, RK-1)."""

    def test_the_two_packages_share_no_path_file_name_or_property_name(self) -> None:
        """The control: they really are written for two different profiles.

        One string is shared and has to be: the file name that follows **neither**
        convention, which is how each package carries a document the data-card check skips.
        Its path still differs, because the vault root does.
        """
        shared = profile_strings(PAIR_A) & profile_strings(PAIR_B)

        assert shared == {f"{UNNUMBERED_PART}.SLDPRT"}, shared
        for case_name, profile in MATCHED_PAIR.items():
            pattern = fixture_profile(profile).part_number.pattern
            assert not part_number_matches(pattern, f"{UNNUMBERED_PART}.SLDPRT"), case_name

    def test_each_package_names_its_own_profile_in_its_case_file(self) -> None:
        for case_name, profile in MATCHED_PAIR.items():
            case = json.loads(
                (FIXTURES_DIR / case_name / "case.json").read_text(encoding="utf-8")
            )
            assert case["kwargs"] == {"profile": profile}, case_name

    def test_the_two_own_profile_runs_produce_the_same_coverage_rows(self) -> None:
        """SC-005: the same sixteen checks land in the same buckets over the same documents."""
        first = graded(PAIR_A)
        second = graded(PAIR_B)

        assert coverage_shape(first) == coverage_shape(second)

    def test_the_two_own_profile_runs_produce_the_same_findings_by_check_id(self) -> None:
        first = graded(PAIR_A)
        second = graded(PAIR_B)

        assert findings_shape(first) == findings_shape(second)
        assert [finding["check"] for finding in first["findings"]] == [
            finding["check"] for finding in second["findings"]
        ]

    def test_the_two_own_profile_runs_reach_the_same_verdict(self) -> None:
        first, second = graded(PAIR_A)["verdict"], graded(PAIR_B)["verdict"]

        assert first == second

    @pytest.mark.parametrize("case_name", sorted(MATCHED_PAIR))
    def test_every_check_is_bound_and_all_sixteen_are_accounted_for(
        self, case_name: str
    ) -> None:
        result = graded(case_name)

        assert result["unavailable_checks"] == []
        assert {row["check"] for row in result["coverage"]} | {
            finding["check"] for finding in result["findings"]
        } == set(RULES) | {STANDARDS_FAMILY.summary_check}

    # --- the control: the profile decides, not the package ---------------------------------

    def test_grading_a_package_against_the_other_profile_changes_what_it_says(self) -> None:
        """Without this, a reviewer that read no profile at all would pass the pair."""
        own = graded(PAIR_A)
        other = graded_against(PAIR_A, MATCHED_PAIR[PAIR_B])

        assert coverage_shape(own) != coverage_shape(other)
        assert findings_shape(own) != findings_shape(other)

    def test_the_other_profile_finds_no_export_control_phrase(self) -> None:
        """The phrase in the package is profile A's, and profile B names another."""
        other = graded_against(PAIR_A, MATCHED_PAIR[PAIR_B])
        drawing_id = drawing_document(package_of(PAIR_A))

        assert buckets_of(other, NO_ITAR).get("checked") == [drawing_id]
        assert NO_ITAR not in findings_by_check(other)

    def test_the_other_profile_recognizes_no_file_name_so_no_data_card_is_graded(self) -> None:
        """`part_number.pattern` decides which documents the data card is read on."""
        other = graded_against(PAIR_A, MATCHED_PAIR[PAIR_B])
        every_document = sorted(row.document_id for row in package_of(PAIR_A).documents)

        assert sorted(buckets_of(other, DATA_CARD)["skipped"]) == every_document
        assert DATA_CARD not in findings_by_check(other)

    def test_the_other_profile_names_a_configuration_the_parts_do_not_carry(self) -> None:
        """`material.configuration` decides which configuration the material is read in."""
        other = graded_against(PAIR_A, MATCHED_PAIR[PAIR_B])
        parts = sorted(
            row.document_id for row in package_of(PAIR_A).documents if row.kind == "part"
        )

        assert sorted(buckets_of(other, MATERIAL_ASSIGNED)["unresolved"]) == parts

    def test_the_two_cross_gradings_agree_with_each_other(self) -> None:
        """The mismatch is symmetric, because the two packages are one design twice."""
        first = graded_against(PAIR_A, MATCHED_PAIR[PAIR_B])
        second = graded_against(PAIR_B, MATCHED_PAIR[PAIR_A])

        assert coverage_shape(first) == coverage_shape(second)
        assert findings_shape(first) == findings_shape(second)
