"""What the four standards goldens are for (T053 to T056).

`test_golden.py` pins every byte each fixture produces; this module pins the *claims* the
four fixtures exist to make, so a baseline regenerated by hand cannot quietly accept a
different grading. Each test names the task and the success criterion it measures.

Every case runs exactly what the golden harness runs - the callable its own `case.json`
names, over its own `package.json` - so the two cannot drift apart.

**The four drawing checks are registered and unbound until US2 (T066).** `contracts/rules.md`
puts them in the catalogue and `tools/standards_checks.py` reports a check with no evaluator
as **unresolved** over every document its scope applies to, naming that nothing about it is
claimed, and lists it in `unavailable_checks`. So on a fixture that carries a drawing they
are four unresolved rows on the drawing document, and on one that carries none they are
four `out_of_scope` rows - never skipped, and never absent.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from swreview.checks.standards.registry import RULES, STANDARDS_FAMILY
from swreview.ir.loader import load_package
from swreview.ir.models import EvidencePackage
from tests.golden.test_golden import FIXTURES_DIR, resolve_callable

DRAWING_CHECKS: tuple[str, ...] = (
    "standards.drawing.dimensions_not_overridden",
    "standards.drawing.annotations_not_dangling",
    "standards.drawing.revision_matches",
    "standards.drawing.no_itar_statement",
)
"""The four checks US2 binds. Until then they are unbound, not absent."""

TRANSPARENCY = "standards.assembly.not_transparent"
MATE_REFERENCES = "standards.assembly.mate_references"
FULLY_MATED = "standards.assembly.fully_mated"
DATA_CARD = "standards.document.data_card_complete"

PART_CHECKS: tuple[str, ...] = tuple(
    check for check, rule in RULES.items() if rule.scope == "part"
)

UNREADABLE_SKETCH_PART = "MR-13005.SLDPRT"
UNREADABLE_MASS_PART = "MR-13004.SLDPRT"
"""The two parts `standards-unknown` seeds one unreadable signal each on (SC-003)."""

US1_CHECKS: tuple[str, ...] = tuple(check for check in RULES if check not in DRAWING_CHECKS)
"""The twelve checks US1 delivers: the sixteen less the four drawing ones."""

MODEL_SCOPE_CHECKS: tuple[str, ...] = tuple(
    check for check, rule in RULES.items() if rule.scope in ("assembly", "document")
)
"""The seven assembly-scope checks and the one document-scope check.

The eight a sub-assembly document is graded by, which is what T056's counting rule is
asked of: reached twice, graded once.
"""

UNKNOWN_UNRESOLVED: frozenset[str] = frozenset(
    {
        MATE_REFERENCES,
        FULLY_MATED,
        TRANSPARENCY,
        "standards.part.sketches_fully_defined",
        "standards.part.material_assigned",
        "standards.part.rebuild_errors",
        "standards.part.cut_list_excluded",
        DATA_CARD,
    }
)
"""T055's acceptance: the eight checks `standards-unknown` leaves unresolved, named here.

Named rather than read back off the same run, because "the verdict lists what the coverage
rows say" is true of any set, the empty one included. The four drawing ids are absent
because that fixture carries no drawing: they are `out_of_scope` there, not unresolved.
"""

SEEDED_FINDINGS: dict[str, int] = {
    "standards.assembly.not_exploded": 1,
    "standards.assembly.rebuild_errors": 1,
    "standards.assembly.mate_references": 1,
    "standards.assembly.one_fixed": 1,
    "standards.assembly.fully_mated": 1,
    "standards.assembly.not_hidden": 1,
    "standards.part.sketches_fully_defined": 1,
    "standards.part.rebuild_errors": 1,
    "standards.part.material_assigned": 1,
    "standards.part.cut_list_excluded": 1,
    "standards.document.data_card_complete": 1,
}
"""T053's first acceptance line: eleven findings, one per US1 check except the transparency
one, which is unresolved while `TRANSPARENCY_POLARITY` is unsettled (SC-014). The four
drawing ids join this map with T070, once their evaluators exist."""


def graded(case_name: str) -> dict[str, Any]:
    """One golden case, run the way `test_golden.py` runs it."""
    directory = FIXTURES_DIR / case_name
    case = json.loads((directory / "case.json").read_text(encoding="utf-8"))
    function = resolve_callable(case["callable"])
    return function(load_package(directory).package, **case.get("kwargs", {}))


def package_of(case_name: str) -> EvidencePackage:
    return load_package(FIXTURES_DIR / case_name).package


def findings_by_check(result: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    by_check: dict[str, list[dict[str, Any]]] = {}
    for finding in result["findings"]:
        by_check.setdefault(finding["check"], []).append(finding)
    return by_check


def buckets_of(result: dict[str, Any], check: str) -> dict[str, list[str]]:
    """Which documents `check` landed in which bucket, off the coverage rows."""
    landed: dict[str, list[str]] = {}
    for row in result["coverage"]:
        if row["check"] != check:
            continue
        landed.setdefault(row["bucket"], []).extend(row["scope"]["document_ids"])
    return landed


def unresolved_checks(result: dict[str, Any]) -> set[str]:
    return {
        row["check"]
        for row in result["coverage"]
        if row["bucket"] == "unresolved" and row["check"] in RULES
    }


def document_of(finding: dict[str, Any]) -> str:
    return str(finding["provenance"][0]["document_id"])


def sub_assemblies(package: EvidencePackage) -> list[str]:
    """Every assembly below the top one, which is what difference h's rows name.

    The top assembly is the root document when a model was opened, and the one the root
    drawing's views reference when a drawing was: `design.root_assembly_document_id` holds
    the **drawing's** id for a drawing root, which is the feature 003 misnomer
    `contracts/ir-additions.md` section 7 keeps deliberately.
    """
    tops = {
        package.design.root_assembly_document_id,
        *(
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id is not None
        ),
    }
    return [
        row.document_id
        for row in package.documents
        if row.kind == "assembly" and row.document_id not in tops
    ]


def document_id_for(package: EvidencePackage, file_name: str) -> str:
    return next(row.document_id for row in package.documents if row.file_name == file_name)


def reached_only_through_unresolved_instances(package: EvidencePackage) -> set[str]:
    """Documents every instance of which is suppressed, lightweight or unloaded (FR-005)."""
    states: dict[str, set[str]] = {}
    for row in package.components:
        states.setdefault(row.document_id, set()).add(row.suppression)
    return {
        document_id
        for document_id, seen in states.items()
        if seen and "resolved" not in seen
    }


def full_paths_of(package: EvidencePackage, component_ids: list[str]) -> list[str]:
    """The occurrence path of each instance, in the order the finding named them.

    The finding shape T047 pins is id-only: `component_ids` and the `inputs` lines carry
    ids and the scope document, and neither they nor the `subjects` rows beside them carry
    `full_path`. So T056's "every path" is named *through* those ids, and this is what
    resolves them - a named id that no instance carries would raise here.
    """
    by_id = {row.id: row.full_path for row in package.components}
    return [by_id[component_id] for component_id in component_ids]


def shared_document_id(package: EvidencePackage) -> str:
    """The one assembly document two different parent instances both reach."""
    parents: dict[str, set[str | None]] = {}
    for row in package.components:
        parents.setdefault(row.document_id, set()).add(row.parent_id)
    assemblies = {row.document_id for row in package.documents if row.kind == "assembly"}
    shared = [
        document_id
        for document_id, seen in parents.items()
        if document_id in assemblies and len(seen) > 1
    ]
    assert len(shared) == 1, shared
    return shared[0]


@pytest.fixture(scope="module")
def seeded() -> dict[str, Any]:
    return graded("standards-seeded")


@pytest.fixture(scope="module")
def compliant() -> dict[str, Any]:
    return graded("standards-compliant")


@pytest.fixture(scope="module")
def flat() -> dict[str, Any]:
    return graded("standards-compliant-flat")


@pytest.fixture(scope="module")
def unknown() -> dict[str, Any]:
    return graded("standards-unknown")


@pytest.fixture(scope="module")
def multiplicity() -> dict[str, Any]:
    return graded("standards-multiplicity")


# --- T053: standards-seeded ---------------------------------------------------------------


class TestSeeded:
    """One violation, in one document, of each of the sixteen checks (SC-001, SC-006)."""

    def test_each_us1_check_but_the_transparency_one_produces_exactly_one_finding(
        self, seeded: dict[str, Any]
    ) -> None:
        counts = {check: len(rows) for check, rows in findings_by_check(seeded).items()}

        assert counts == SEEDED_FINDINGS

    def test_eleven_findings_and_no_twelfth(self, seeded: dict[str, Any]) -> None:
        assert len(seeded["findings"]) == 11

    def test_the_transparency_check_is_one_unresolved_row_and_no_finding(
        self, seeded: dict[str, Any]
    ) -> None:
        landed = buckets_of(seeded, TRANSPARENCY)

        assert set(landed) - {"out_of_scope"} == {"unresolved"}
        assert len(landed["unresolved"]) == 1

    def test_no_seventeenth_check_result(self, seeded: dict[str, Any]) -> None:
        rows = [row["check"] for row in seeded["checks"]]

        assert rows == list(RULES)
        assert STANDARDS_FAMILY.summary_check not in rows

    def test_the_summary_item_is_present_and_is_not_counted_as_a_check(
        self, seeded: dict[str, Any]
    ) -> None:
        summaries = [
            row for row in seeded["coverage"] if row["check"] == STANDARDS_FAMILY.summary_check
        ]

        assert len(summaries) == 1
        assert STANDARDS_FAMILY.summary_check not in RULES

    def test_every_finding_carries_the_status_its_check_severity_maps_to(
        self, seeded: dict[str, Any]
    ) -> None:
        for finding in seeded["findings"]:
            rule = RULES[finding["check"]]
            expected = STANDARDS_FAMILY.status_by_severity[str(rule.severity)][0]
            assert finding["status"] == expected, finding["check"]

    def test_the_failing_part_is_reached_through_twenty_instances(
        self, seeded: dict[str, Any]
    ) -> None:
        """SC-006's first half: one finding per document, naming every instance."""
        part_findings = [
            finding
            for finding in seeded["findings"]
            if finding["check"].startswith("standards.part.")
        ]

        assert len(part_findings) == 4
        for finding in part_findings:
            assert len(finding["component_ids"]) == 20, finding["check"]

    def test_the_seeded_drawing_carries_six_overridden_dimensions(self) -> None:
        """SC-006's second half, seeded now and graded by T070."""
        package = package_of("standards-seeded")
        overridden = [
            dimension
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            for dimension in view.display_dimensions
            if dimension.is_overridden
        ]

        assert len(overridden) == 6
        assert len({dimension.view_id for dimension in overridden}) == 1

    def test_the_package_holds_exactly_one_assembly_document_and_one_drawing(self) -> None:
        """SC-001: a second assembly would add difference-h rows the counts exclude."""
        package = package_of("standards-seeded")
        assemblies = [row for row in package.documents if row.kind == "assembly"]
        drawings = [row for row in package.documents if row.kind == "drawing"]

        assert len(assemblies) == 1
        assert len(drawings) == 1

    def test_the_drawing_views_reference_that_same_root_assembly(self) -> None:
        package = package_of("standards-seeded")
        assembly = next(row.document_id for row in package.documents if row.kind == "assembly")
        referenced = {
            view.referenced_document_id
            for record in package.drawing_records
            for sheet in record.sheets
            for view in sheet.views
            if view.referenced_document_id is not None
        }

        assert referenced == {assembly}

    def test_two_violations_are_seeded_at_depth(self, seeded: dict[str, Any]) -> None:
        """Difference z: a defect inside a folder or a derived feature is still a subject."""
        package = package_of("standards-seeded")
        nested = {row.id for row in package.features if row.folder_id is not None}
        by_check = findings_by_check(seeded)

        for check in ("standards.part.sketches_fully_defined", "standards.part.rebuild_errors"):
            named = {entry.split()[1] for entry in by_check[check][0]["inputs"]}
            assert named & nested, check

    def test_the_four_drawing_checks_are_unresolved_over_the_drawing_and_unavailable(
        self, seeded: dict[str, Any]
    ) -> None:
        package = package_of("standards-seeded")
        drawing_id = next(row.document_id for row in package.documents if row.kind == "drawing")
        for check in DRAWING_CHECKS:
            landed = buckets_of(seeded, check)
            assert landed.get("unresolved") == [drawing_id], check

        assert [row["check"] for row in seeded["unavailable_checks"]] == list(DRAWING_CHECKS)

    def test_the_verdict_is_not_ready_and_carries_the_unresolved_ids(
        self, seeded: dict[str, Any]
    ) -> None:
        verdict = seeded["verdict"]

        assert verdict["state"] == "not_ready"
        assert verdict["counts"]["error"] == 11
        assert TRANSPARENCY in verdict["unresolved_check_ids"]


# --- T054: standards-compliant and standards-compliant-flat -------------------------------


class TestCompliant:
    """SC-002's model half: zero findings, and what `ready` costs."""

    def test_the_multi_level_fixture_produces_zero_findings(
        self, compliant: dict[str, Any]
    ) -> None:
        assert compliant["findings"] == []

    def test_the_multi_level_fixture_carries_parts_sub_assemblies_and_a_drawing(self) -> None:
        package = package_of("standards-compliant")
        kinds = {row.kind for row in package.documents}

        assert kinds == {"part", "assembly", "drawing"}
        assert sub_assemblies(package)

    @pytest.mark.parametrize(
        ("case", "known_gaps"),
        [
            ("compliant", frozenset({MATE_REFERENCES, FULLY_MATED, TRANSPARENCY})),
            ("flat", frozenset({TRANSPARENCY})),
        ],
    )
    def test_every_us1_check_is_checked_or_skipped_with_a_stated_reason(
        self,
        case: str,
        known_gaps: frozenset[str],
        request: pytest.FixtureRequest,
    ) -> None:
        """T054's acceptance line, asked of **both** compliant fixtures.

        `standards-compliant-flat` is the one the Phase 3 Independent Test names - the
        single-level fixture of spec.md:21 - so the assertion has to be made there too: a
        check that emitted no coverage row at all for that package would be the silent
        skip the hard rules forbid, and `findings == []` cannot see it. The flat fixture
        has no sub-assembly, so the two difference-h gaps do not arise there and only the
        unsettled transparency polarity is left unresolved.
        """
        result: dict[str, Any] = request.getfixturevalue(case)
        for check in US1_CHECKS:
            landed = buckets_of(result, check)
            assert landed, check
            graded_buckets = set(landed) - {"out_of_scope"}
            if check in known_gaps:
                assert "unresolved" in graded_buckets, check
            else:
                assert graded_buckets <= {"checked", "skipped"}, check
        for row in result["coverage"]:
            assert row["reason"], row["check"]

    def test_the_two_known_gaps_name_each_sub_assembly(self, compliant: dict[str, Any]) -> None:
        subs = sub_assemblies(package_of("standards-compliant"))

        assert subs
        assert buckets_of(compliant, MATE_REFERENCES)["unresolved"] == subs
        assert buckets_of(compliant, FULLY_MATED)["unresolved"] == subs

    def test_the_unresolved_ids_are_the_two_gaps_the_polarity_and_the_unbound_drawings(
        self, compliant: dict[str, Any]
    ) -> None:
        """T069a replaces the drawing half of this set once the evaluators exist."""
        expected = {MATE_REFERENCES, FULLY_MATED, TRANSPARENCY, *DRAWING_CHECKS}

        assert unresolved_checks(compliant) == expected
        assert set(compliant["verdict"]["unresolved_check_ids"]) == expected

    def test_the_multi_level_verdict_is_ready_coverage_incomplete(
        self, compliant: dict[str, Any]
    ) -> None:
        assert compliant["verdict"]["state"] == "ready_coverage_incomplete"
        assert compliant["verdict"]["counts"]["error"] == 0

    def test_the_flat_fixture_produces_zero_findings(self, flat: dict[str, Any]) -> None:
        assert flat["findings"] == []

    def test_the_flat_fixture_has_no_sub_assembly_and_one_drawing(self) -> None:
        package = package_of("standards-compliant-flat")
        drawings = [row for row in package.documents if row.kind == "drawing"]

        assert sub_assemblies(package) == []
        assert len(drawings) == 1

    def test_the_flat_fixture_is_unresolved_only_where_this_build_cannot_answer(
        self, flat: dict[str, Any]
    ) -> None:
        """SC-014 removes the polarity row and T066 the four drawing ones; then `ready`."""
        assert unresolved_checks(flat) == {TRANSPARENCY, *DRAWING_CHECKS}

    def test_the_flat_headline_carries_no_no_drawing_note(self, flat: dict[str, Any]) -> None:
        assert "no drawing graded" not in flat["verdict"]["notes"]

    def test_every_compliant_drawing_sheet_records_a_sheet_format_view(self) -> None:
        """Without a type-1 view per sheet `no_itar_statement` can never reach `ready`."""
        for case in ("standards-compliant", "standards-compliant-flat"):
            for record in package_of(case).drawing_records:
                for sheet in record.sheets:
                    assert any(view.view_type_raw == 1 for view in sheet.views), sheet.name


# --- T055: standards-unknown (model half) -------------------------------------------------


class TestUnknown:
    """SC-003's model half: unknown stays unknown, and never becomes a pass."""

    def test_the_fixture_is_otherwise_compliant(self, unknown: dict[str, Any]) -> None:
        assert unknown["verdict"]["counts"]["error"] == 0
        assert unknown["findings"] == []

    def test_the_verdict_is_ready_coverage_incomplete_naming_the_unresolved_ids(
        self, unknown: dict[str, Any]
    ) -> None:
        assert unknown["verdict"]["state"] == "ready_coverage_incomplete"
        assert unresolved_checks(unknown) == UNKNOWN_UNRESOLVED
        assert set(unknown["verdict"]["unresolved_check_ids"]) == UNKNOWN_UNRESOLVED

    def test_the_suppressed_and_lightweight_components_are_skipped_with_their_state(
        self, unknown: dict[str, Any]
    ) -> None:
        for check in (
            "standards.assembly.one_fixed",
            "standards.assembly.fully_mated",
            "standards.assembly.not_hidden",
        ):
            reasons = " ".join(
                row["reason"]
                for row in unknown["coverage"]
                if row["check"] == check and row["bucket"] == "skipped"
            )
            assert "suppressed" in reasons, check
            assert "lightweight" in reasons, check

    def test_the_unreadable_sketch_status_is_unresolved_and_that_part_is_not_checked(
        self, unknown: dict[str, Any]
    ) -> None:
        check = "standards.part.sketches_fully_defined"
        part = document_id_for(package_of("standards-unknown"), UNREADABLE_SKETCH_PART)
        landed = buckets_of(unknown, check)
        reasons = [
            row["reason"]
            for row in unknown["coverage"]
            if row["check"] == check and row["bucket"] == "unresolved"
        ]

        assert part in landed["unresolved"]
        assert part not in landed.get("checked", ())
        assert any("constrained status is unavailable" in reason for reason in reasons)

    def test_the_unreadable_mass_override_is_unresolved_and_that_part_is_not_checked(
        self, unknown: dict[str, Any]
    ) -> None:
        check = "standards.part.material_assigned"
        part = document_id_for(package_of("standards-unknown"), UNREADABLE_MASS_PART)
        landed = buckets_of(unknown, check)
        reasons = [
            row["reason"]
            for row in unknown["coverage"]
            if row["check"] == check and row["bucket"] == "unresolved"
        ]

        assert part in landed["unresolved"]
        assert part not in landed.get("checked", ())
        assert any("whether the mass is overridden was not read" in reason for reason in reasons)

    def test_a_document_reached_only_through_unresolved_instances_is_never_graded(
        self, unknown: dict[str, Any]
    ) -> None:
        """FR-005: what the package records about it is not a reading of that document."""
        blocked = reached_only_through_unresolved_instances(package_of("standards-unknown"))

        assert len(blocked) == 2
        for check in (*PART_CHECKS, DATA_CARD):
            landed = buckets_of(unknown, check)
            assert blocked <= set(landed.get("unresolved", ())), check
            assert not blocked & set(landed.get("checked", ())), check
            assert not blocked & set(landed.get("skipped", ())), check

    def test_the_sub_assembly_is_what_the_mate_check_cannot_answer_for(
        self, unknown: dict[str, Any]
    ) -> None:
        subs = sub_assemblies(package_of("standards-unknown"))

        assert subs
        assert buckets_of(unknown, MATE_REFERENCES)["unresolved"] == subs

    def test_the_four_drawing_checks_are_out_of_scope_because_no_drawing_is_graded(
        self, unknown: dict[str, Any]
    ) -> None:
        for check in DRAWING_CHECKS:
            assert set(buckets_of(unknown, check)) == {"out_of_scope"}, check
        assert "no drawing graded" in unknown["verdict"]["notes"]


# --- T056: standards-multiplicity ---------------------------------------------------------


class TestMultiplicity:
    """SC-006's counting rule: per document, not per instance, parent or subject."""

    def test_one_sub_assembly_appears_under_two_parents(self) -> None:
        package = package_of("standards-multiplicity")
        shared = [
            row for row in package.components if row.document_id == shared_document_id(package)
        ]

        assert len(shared) == 2
        assert len({row.parent_id for row in shared}) == 2

    def test_each_failing_check_produces_exactly_one_finding_per_document(
        self, multiplicity: dict[str, Any]
    ) -> None:
        pairs = [
            (finding["check"], document_of(finding)) for finding in multiplicity["findings"]
        ]

        assert len(pairs) == len(set(pairs))

    def test_the_error_count_equals_the_number_of_distinct_failing_pairs(
        self, multiplicity: dict[str, Any]
    ) -> None:
        pairs = {(finding["check"], document_of(finding)) for finding in multiplicity["findings"]}

        assert multiplicity["verdict"]["counts"]["error"] == len(pairs)
        assert len(pairs) == 4

    def test_the_shared_sub_assembly_gets_one_set_of_rows_naming_both_instances(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")
        shared = shared_document_id(package)
        instances = [row.id for row in package.components if row.document_id == shared]
        findings = [
            finding for finding in multiplicity["findings"] if document_of(finding) == shared
        ]

        assert len(findings) == 3
        for finding in findings:
            assert finding["component_ids"] == instances, finding["check"]

    def test_the_shared_sub_assembly_is_accounted_for_once_per_check_and_not_twice(
        self, multiplicity: dict[str, Any]
    ) -> None:
        """T056's "one set of rows and not two", measured on the rows and not the findings.

        Reached twice, graded once: for each of the eight checks whose scope a sub-assembly
        document matches, the shared document is named by exactly one coverage row **or**
        by exactly one finding - never by two rows, never by a row and a finding both, and
        never by none, which would be the silent skip the hard rules forbid.
        """
        shared = shared_document_id(package_of("standards-multiplicity"))

        assert len(MODEL_SCOPE_CHECKS) == 8
        for check in MODEL_SCOPE_CHECKS:
            rows = [
                row
                for row in multiplicity["coverage"]
                if row["check"] == check and shared in row["scope"]["document_ids"]
            ]
            findings = [
                finding
                for finding in multiplicity["findings"]
                if finding["check"] == check and document_of(finding) == shared
            ]
            assert len(rows) + len(findings) == 1, (check, rows, findings)

    def test_the_shared_sub_assembly_s_findings_name_both_occurrence_paths(
        self, multiplicity: dict[str, Any]
    ) -> None:
        """T056's "every path": the ids each finding names resolve to the two occurrences.

        `MR-40004` is reached once under `MR-40002` and once under `MR-40003`, and an
        engineer reading `cmp:0004` and `cmp:0009` has to be able to tell which two
        occurrences those are. The finding shape T047 pins is id-only, so the paths are
        named through the ids (see `full_paths_of`) rather than carried beside them - if
        that changes, this is the assertion to move onto whatever field carries them.
        """
        package = package_of("standards-multiplicity")
        shared = shared_document_id(package)
        findings = [
            finding for finding in multiplicity["findings"] if document_of(finding) == shared
        ]

        assert findings
        for finding in findings:
            paths = full_paths_of(package, finding["component_ids"])
            parents = {path.rsplit("/", 1)[0] for path in paths}
            assert len(paths) == 2, finding["check"]
            assert len(set(paths)) == 2, (finding["check"], paths)
            assert len(parents) == 2, (finding["check"], paths)

    def test_the_many_times_used_part_gets_one_finding_naming_every_instance(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")
        findings = [
            finding
            for finding in multiplicity["findings"]
            if finding["check"] == "standards.part.material_assigned"
        ]

        assert len(findings) == 1
        instances = [
            row.id for row in package.components if row.document_id == document_of(findings[0])
        ]
        assert len(instances) == 8
        assert findings[0]["component_ids"] == instances
        paths = full_paths_of(package, findings[0]["component_ids"])
        assert len(set(paths)) == 8, paths
        assert len({path.rsplit("/", 1)[0] for path in paths}) == 2, paths

    def test_the_fixture_carries_no_drawing_and_its_drawing_rows_are_out_of_scope(
        self, multiplicity: dict[str, Any]
    ) -> None:
        package = package_of("standards-multiplicity")

        assert not [row for row in package.documents if row.kind == "drawing"]
        for check in DRAWING_CHECKS:
            assert set(buckets_of(multiplicity, check)) == {"out_of_scope"}, check
